// backend/seedMasterDSA.js
require('dotenv').config();
const mongoose = require('mongoose');
const MasterDSAQuestion = require('./models/MasterDSAQuestion');

mongoose.connect(process.env.MONGO_URI).then(() => console.log('DB connected'));

const questions = [
{topicSlug:'arrays',topic:'Arrays & Strings',order:1,globalOrder:1,title:'Two Sum',difficulty:'Easy',
description:'Given an array of integers nums and an integer target, return indices of two numbers that add up to target.',
examples:[{input:'nums=[2,7,11,15], target=9',output:'[0,1]'}],
hint:'Use HashMap — store complement.',approach:'Single pass HashMap lookup.',
java_code:'class Solution{public int[] twoSum(int[] nums,int target){Map<Integer,Integer> m=new HashMap<>();for(int i=0;i<nums.length;i++){int c=target-nums[i];if(m.containsKey(c))return new int[]{m.get(c),i};m.put(nums[i],i);}return new int[]{};}}',
python_code:'def twoSum(nums,target):\n    seen={}\n    for i,n in enumerate(nums):\n        if target-n in seen: return [seen[target-n],i]\n        seen[n]=i',
cpp_code:'vector<int> twoSum(vector<int>&n,int t){unordered_map<int,int>m;for(int i=0;i<n.size();i++){if(m.count(t-n[i]))return{m[t-n[i]],i};m[n[i]]=i;}return{};}',
companies:['TCS','Amazon'],tags:['Array','HashMap'],similarQs:['Three Sum','4Sum'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'HashMap',trick:'Check before insert',leetcodeUrl:'https://leetcode.com/problems/two-sum/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:2,globalOrder:2,title:'Maximum Subarray',difficulty:'Medium',
description:'Find the contiguous subarray with the largest sum.',
examples:[{input:'[-2,1,-3,4,-1,2,1,-5,4]',output:'6'}],
hint:'Reset sum to 0 if negative.',approach:"Kadane's Algorithm.",
java_code:'class Solution{public int maxSubArray(int[] n){int max=n[0],cur=n[0];for(int i=1;i<n.length;i++){cur=Math.max(n[i],cur+n[i]);max=Math.max(max,cur);}return max;}}',
python_code:'def maxSubArray(n):\n    cur=mx=n[0]\n    for x in n[1:]:\n        cur=max(x,cur+x);mx=max(mx,cur)\n    return mx',
cpp_code:'int maxSubArray(vector<int>&n){int cur=n[0],r=n[0];for(int i=1;i<n.size();i++){cur=max(n[i],cur+n[i]);r=max(r,cur);}return r;}',
companies:['TCS','Infosys'],tags:['Array','DP'],similarQs:['Max Product Subarray'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:"Kadane's",trick:'Restart if cur<0',leetcodeUrl:'https://leetcode.com/problems/maximum-subarray/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:3,globalOrder:3,title:'Best Time to Buy and Sell Stock',difficulty:'Easy',
description:'Find max profit from buying then selling one share.',
examples:[{input:'[7,1,5,3,6,4]',output:'5'}],
hint:'Track min price so far.',approach:'Single pass min tracking.',
java_code:'class Solution{public int maxProfit(int[] p){int mn=Integer.MAX_VALUE,pr=0;for(int x:p){mn=Math.min(mn,x);pr=Math.max(pr,x-mn);}return pr;}}',
python_code:'def maxProfit(p):\n    mn,pr=float("inf"),0\n    for x in p:\n        mn=min(mn,x);pr=max(pr,x-mn)\n    return pr',
cpp_code:'int maxProfit(vector<int>&p){int mn=INT_MAX,r=0;for(int x:p){mn=min(mn,x);r=max(r,x-mn);}return r;}',
companies:['Amazon','TCS'],tags:['Array','Greedy'],similarQs:['Buy Sell II'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Min tracking',trick:'One pass min so far',leetcodeUrl:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:4,globalOrder:4,title:'Contains Duplicate',difficulty:'Easy',
description:'Return true if any value appears at least twice in the array.',
examples:[{input:'[1,2,3,1]',output:'true'}],
hint:'Use a Set.',approach:'Add to set, if already present return true.',
java_code:'class Solution{public boolean containsDuplicate(int[] n){Set<Integer> s=new HashSet<>();for(int x:n){if(!s.add(x))return true;}return false;}}',
python_code:'def containsDuplicate(n):\n    return len(set(n))!=len(n)',
cpp_code:'bool containsDuplicate(vector<int>&n){unordered_set<int>s;for(int x:n){if(s.count(x))return true;s.insert(x);}return false;}',
companies:['TCS','Wipro'],tags:['Array','HashSet'],similarQs:['Contains Duplicate II'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'Set lookup',trick:'set size vs array size',leetcodeUrl:'https://leetcode.com/problems/contains-duplicate/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:5,globalOrder:5,title:'Product of Array Except Self',difficulty:'Medium',
description:'Return array where output[i] equals product of all elements except nums[i], without division.',
examples:[{input:'[1,2,3,4]',output:'[24,12,8,6]'}],
hint:'Prefix and suffix products.',approach:'Two passes — left products then right products.',
java_code:'class Solution{public int[] productExceptSelf(int[] n){int L=n.length;int[] res=new int[L];res[0]=1;for(int i=1;i<L;i++)res[i]=res[i-1]*n[i-1];int r=1;for(int i=L-1;i>=0;i--){res[i]*=r;r*=n[i];}return res;}}',
python_code:'def productExceptSelf(n):\n    L=len(n);res=[1]*L\n    for i in range(1,L): res[i]=res[i-1]*n[i-1]\n    r=1\n    for i in range(L-1,-1,-1):\n        res[i]*=r;r*=n[i]\n    return res',
cpp_code:'vector<int> productExceptSelf(vector<int>&n){int L=n.size();vector<int>res(L,1);for(int i=1;i<L;i++)res[i]=res[i-1]*n[i-1];int r=1;for(int i=L-1;i>=0;i--){res[i]*=r;r*=n[i];}return res;}',
companies:['Amazon','Flipkart'],tags:['Array','Prefix Sum'],similarQs:['Trapping Rain Water'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Prefix-Suffix',trick:'Output array doubles as prefix array',leetcodeUrl:'https://leetcode.com/problems/product-of-array-except-self/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:6,globalOrder:6,title:'Container With Most Water',difficulty:'Medium',
description:'Given heights array, find two lines that form container with most water.',
examples:[{input:'[1,8,6,2,5,4,8,3,7]',output:'49'}],
hint:'Two pointers from both ends.',approach:'Move pointer with smaller height inward.',
java_code:'class Solution{public int maxArea(int[] h){int l=0,r=h.length-1,max=0;while(l<r){max=Math.max(max,Math.min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}return max;}}',
python_code:'def maxArea(h):\n    l,r,mx=0,len(h)-1,0\n    while l<r:\n        mx=max(mx,min(h[l],h[r])*(r-l))\n        if h[l]<h[r]: l+=1\n        else: r-=1\n    return mx',
cpp_code:'int maxArea(vector<int>&h){int l=0,r=h.size()-1,mx=0;while(l<r){mx=max(mx,min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}return mx;}',
companies:['Amazon'],tags:['Array','Two Pointer'],similarQs:['Trapping Rain Water'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two Pointer',trick:'Always move the shorter wall',leetcodeUrl:'https://leetcode.com/problems/container-with-most-water/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:7,globalOrder:7,title:'3Sum',difficulty:'Medium',
description:'Find all unique triplets that sum to zero.',
examples:[{input:'[-1,0,1,2,-1,-4]',output:'[[-1,-1,2],[-1,0,1]]'}],
hint:'Sort then two-pointer for each fixed element.',approach:'Sort array. Fix one element, two-pointer for remaining two.',
java_code:'class Solution{public List<List<Integer>> threeSum(int[] n){Arrays.sort(n);List<List<Integer>> res=new ArrayList<>();for(int i=0;i<n.length-2;i++){if(i>0&&n[i]==n[i-1])continue;int l=i+1,r=n.length-1;while(l<r){int s=n[i]+n[l]+n[r];if(s==0){res.add(Arrays.asList(n[i],n[l],n[r]));while(l<r&&n[l]==n[l+1])l++;while(l<r&&n[r]==n[r-1])r--;l++;r--;}else if(s<0)l++;else r--;}}return res;}}',
python_code:'def threeSum(n):\n    n.sort();res=[]\n    for i in range(len(n)-2):\n        if i>0 and n[i]==n[i-1]: continue\n        l,r=i+1,len(n)-1\n        while l<r:\n            s=n[i]+n[l]+n[r]\n            if s==0:\n                res.append([n[i],n[l],n[r]])\n                while l<r and n[l]==n[l+1]: l+=1\n                while l<r and n[r]==n[r-1]: r-=1\n                l+=1;r-=1\n            elif s<0: l+=1\n            else: r-=1\n    return res',
cpp_code:'vector<vector<int>> threeSum(vector<int>&n){sort(n.begin(),n.end());vector<vector<int>>res;for(int i=0;i<(int)n.size()-2;i++){if(i>0&&n[i]==n[i-1])continue;int l=i+1,r=n.size()-1;while(l<r){int s=n[i]+n[l]+n[r];if(s==0){res.push_back({n[i],n[l],n[r]});while(l<r&&n[l]==n[l+1])l++;while(l<r&&n[r]==n[r-1])r--;l++;r--;}else if(s<0)l++;else r--;}}return res;}',
companies:['Amazon','TCS'],tags:['Array','Two Pointer'],similarQs:['Two Sum','4Sum'],timeComplex:'O(n^2)',spaceComplex:'O(1)',pattern:'Sort + Two Pointer',trick:'Skip duplicates to avoid repeated triplets',leetcodeUrl:'https://leetcode.com/problems/3sum/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:8,globalOrder:8,title:'Sliding Window Maximum',difficulty:'Hard',
description:'Return the max value in each sliding window of size k.',
examples:[{input:'nums=[1,3,-1,-3,5,3,6,7], k=3',output:'[3,3,5,5,6,7]'}],
hint:'Use a deque storing indices, keep it decreasing.',approach:'Monotonic deque — remove smaller elements from back, expired from front.',
java_code:'class Solution{public int[] maxSlidingWindow(int[] n,int k){Deque<Integer> dq=new ArrayDeque<>();int[] res=new int[n.length-k+1];for(int i=0;i<n.length;i++){while(!dq.isEmpty()&&dq.peekFirst()<i-k+1)dq.pollFirst();while(!dq.isEmpty()&&n[dq.peekLast()]<n[i])dq.pollLast();dq.offerLast(i);if(i>=k-1)res[i-k+1]=n[dq.peekFirst()];}return res;}}',
python_code:'from collections import deque\ndef maxSlidingWindow(n,k):\n    dq=deque();res=[]\n    for i,x in enumerate(n):\n        while dq and dq[0]<i-k+1: dq.popleft()\n        while dq and n[dq[-1]]<x: dq.pop()\n        dq.append(i)\n        if i>=k-1: res.append(n[dq[0]])\n    return res',
cpp_code:'vector<int> maxSlidingWindow(vector<int>&n,int k){deque<int>dq;vector<int>res;for(int i=0;i<(int)n.size();i++){while(!dq.empty()&&dq.front()<i-k+1)dq.pop_front();while(!dq.empty()&&n[dq.back()]<n[i])dq.pop_back();dq.push_back(i);if(i>=k-1)res.push_back(n[dq.front()]);}return res;}',
companies:['Google','Amazon'],tags:['Array','Sliding Window','Deque'],similarQs:['Min Window Substring'],timeComplex:'O(n)',spaceComplex:'O(k)',pattern:'Monotonic Deque',trick:'Deque stores indices not values',leetcodeUrl:'https://leetcode.com/problems/sliding-window-maximum/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:9,globalOrder:9,title:'Valid Anagram',difficulty:'Easy',
description:'Given two strings, determine if t is an anagram of s.',
examples:[{input:'s="anagram", t="nagaram"',output:'true'}],
hint:'Count character frequencies.',approach:'Use a frequency array of size 26.',
java_code:'class Solution{public boolean isAnagram(String s,String t){if(s.length()!=t.length())return false;int[] c=new int[26];for(char ch:s.toCharArray())c[ch-\'a\']++;for(char ch:t.toCharArray())c[ch-\'a\']--;for(int x:c)if(x!=0)return false;return true;}}',
python_code:'def isAnagram(s,t):\n    return sorted(s)==sorted(t)',
cpp_code:'bool isAnagram(string s,string t){if(s.size()!=t.size())return false;int c[26]={0};for(char ch:s)c[ch-\'a\']++;for(char ch:t)c[ch-\'a\']--;for(int x:c)if(x)return false;return true;}',
companies:['TCS','Zoho'],tags:['String','HashMap'],similarQs:['Group Anagrams'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Frequency Count',trick:'26-size array beats sorting',leetcodeUrl:'https://leetcode.com/problems/valid-anagram/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:10,globalOrder:10,title:'Group Anagrams',difficulty:'Medium',
description:'Group strings that are anagrams of each other.',
examples:[{input:'["eat","tea","tan","ate","nat","bat"]',output:'[["eat","tea","ate"],["tan","nat"],["bat"]]'}],
hint:'Sort each string as the map key.',approach:'HashMap with sorted-string key, group originals together.',
java_code:'class Solution{public List<List<String>> groupAnagrams(String[] strs){Map<String,List<String>> m=new HashMap<>();for(String s:strs){char[] c=s.toCharArray();Arrays.sort(c);String k=new String(c);m.computeIfAbsent(k,x->new ArrayList<>()).add(s);}return new ArrayList<>(m.values());}}',
python_code:'from collections import defaultdict\ndef groupAnagrams(strs):\n    m=defaultdict(list)\n    for s in strs: m["".join(sorted(s))].append(s)\n    return list(m.values())',
cpp_code:'vector<vector<string>> groupAnagrams(vector<string>&strs){unordered_map<string,vector<string>>m;for(auto&s:strs){string k=s;sort(k.begin(),k.end());m[k].push_back(s);}vector<vector<string>>res;for(auto&p:m)res.push_back(p.second);return res;}',
companies:['Amazon','Flipkart'],tags:['String','HashMap'],similarQs:['Valid Anagram'],timeComplex:'O(n*klogk)',spaceComplex:'O(n*k)',pattern:'HashMap grouping',trick:'Sorted string as canonical key',leetcodeUrl:'https://leetcode.com/problems/group-anagrams/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:11,globalOrder:11,title:'Longest Substring Without Repeating Characters',difficulty:'Medium',
description:'Find length of longest substring without repeating characters.',
examples:[{input:'"abcabcbb"',output:'3'}],
hint:'Sliding window with a set/map.',approach:'Expand right, shrink left when duplicate found.',
java_code:'class Solution{public int lengthOfLongestSubstring(String s){Set<Character> set=new HashSet<>();int l=0,max=0;for(int r=0;r<s.length();r++){while(set.contains(s.charAt(r)))set.remove(s.charAt(l++));set.add(s.charAt(r));max=Math.max(max,r-l+1);}return max;}}',
python_code:'def lengthOfLongestSubstring(s):\n    seen=set();l=mx=0\n    for r,c in enumerate(s):\n        while c in seen:\n            seen.remove(s[l]);l+=1\n        seen.add(c);mx=max(mx,r-l+1)\n    return mx',
cpp_code:'int lengthOfLongestSubstring(string s){unordered_set<char>st;int l=0,mx=0;for(int r=0;r<(int)s.size();r++){while(st.count(s[r])){st.erase(s[l]);l++;}st.insert(s[r]);mx=max(mx,r-l+1);}return mx;}',
companies:['TCS','Wipro','Amazon'],tags:['String','Sliding Window'],similarQs:['Longest Repeating Character Replacement'],timeComplex:'O(n)',spaceComplex:'O(min(n,m))',pattern:'Sliding Window',trick:'Shrink window until valid again',leetcodeUrl:'https://leetcode.com/problems/longest-substring-without-repeating-characters/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:12,globalOrder:12,title:'Longest Common Prefix',difficulty:'Easy',
description:'Find the longest common prefix string amongst an array of strings.',
examples:[{input:'["flower","flow","flight"]',output:'"fl"'}],
hint:'Compare characters column by column.',approach:'Use first string as reference, compare with all others at each index.',
java_code:'class Solution{public String longestCommonPrefix(String[] strs){if(strs.length==0)return "";String pre=strs[0];for(int i=1;i<strs.length;i++){while(!strs[i].startsWith(pre))pre=pre.substring(0,pre.length()-1);}return pre;}}',
python_code:'def longestCommonPrefix(strs):\n    if not strs: return ""\n    pre=strs[0]\n    for s in strs[1:]:\n        while not s.startswith(pre): pre=pre[:-1]\n    return pre',
cpp_code:'string longestCommonPrefix(vector<string>&strs){if(strs.empty())return "";string pre=strs[0];for(int i=1;i<(int)strs.size();i++){while(strs[i].find(pre)!=0)pre=pre.substr(0,pre.size()-1);}return pre;}',
companies:['TCS','Infosys'],tags:['String'],similarQs:['Longest Common Subsequence'],timeComplex:'O(n*m)',spaceComplex:'O(1)',pattern:'Vertical Scanning',trick:'Shrink prefix until it matches',leetcodeUrl:'https://leetcode.com/problems/longest-common-prefix/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:13,globalOrder:13,title:'Move Zeroes',difficulty:'Easy',
description:'Move all zeroes to the end while maintaining relative order of non-zero elements.',
examples:[{input:'[0,1,0,3,12]',output:'[1,3,12,0,0]'}],
hint:'Two pointer — write index for non-zero elements.',approach:'Place non-zero elements forward, fill remaining with zeros.',
java_code:'class Solution{public void moveZeroes(int[] n){int j=0;for(int i=0;i<n.length;i++)if(n[i]!=0)n[j++]=n[i];while(j<n.length)n[j++]=0;}}',
python_code:'def moveZeroes(n):\n    j=0\n    for i in range(len(n)):\n        if n[i]!=0: n[i],n[j]=n[j],n[i];j+=1',
cpp_code:'void moveZeroes(vector<int>&n){int j=0;for(int i=0;i<(int)n.size();i++)if(n[i]!=0)swap(n[j++],n[i]);}',
companies:['Amazon','TCS'],tags:['Array','Two Pointer'],similarQs:['Remove Element'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two Pointer',trick:'Swap instead of overwrite to save writes',leetcodeUrl:'https://leetcode.com/problems/move-zeroes/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:14,globalOrder:14,title:'Find Minimum in Rotated Sorted Array',difficulty:'Medium',
description:'Find the minimum element in a rotated sorted array with no duplicates.',
examples:[{input:'[3,4,5,1,2]',output:'1'}],
hint:'Binary search — compare mid with right.',approach:'If nums[mid]>nums[right], min is in right half, else left half.',
java_code:'class Solution{public int findMin(int[] n){int l=0,r=n.length-1;while(l<r){int m=(l+r)/2;if(n[m]>n[r])l=m+1;else r=m;}return n[l];}}',
python_code:'def findMin(n):\n    l,r=0,len(n)-1\n    while l<r:\n        m=(l+r)//2\n        if n[m]>n[r]: l=m+1\n        else: r=m\n    return n[l]',
cpp_code:'int findMin(vector<int>&n){int l=0,r=n.size()-1;while(l<r){int m=(l+r)/2;if(n[m]>n[r])l=m+1;else r=m;}return n[l];}',
companies:['Amazon','Google'],tags:['Array','Binary Search'],similarQs:['Search in Rotated Array'],timeComplex:'O(log n)',spaceComplex:'O(1)',pattern:'Binary Search Variant',trick:'Compare mid with right end, not left',leetcodeUrl:'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:15,globalOrder:15,title:'Search in Rotated Sorted Array',difficulty:'Medium',
description:'Search target in a rotated sorted array, return index or -1.',
examples:[{input:'nums=[4,5,6,7,0,1,2], target=0',output:'4'}],
hint:'One half is always sorted — check which one.',approach:'Binary search with extra check for sorted half.',
java_code:'class Solution{public int search(int[] n,int t){int l=0,r=n.length-1;while(l<=r){int m=(l+r)/2;if(n[m]==t)return m;if(n[l]<=n[m]){if(t>=n[l]&&t<n[m])r=m-1;else l=m+1;}else{if(t>n[m]&&t<=n[r])l=m+1;else r=m-1;}}return -1;}}',
python_code:'def search(n,t):\n    l,r=0,len(n)-1\n    while l<=r:\n        m=(l+r)//2\n        if n[m]==t: return m\n        if n[l]<=n[m]:\n            if n[l]<=t<n[m]: r=m-1\n            else: l=m+1\n        else:\n            if n[m]<t<=n[r]: l=m+1\n            else: r=m-1\n    return -1',
cpp_code:'int search(vector<int>&n,int t){int l=0,r=n.size()-1;while(l<=r){int m=(l+r)/2;if(n[m]==t)return m;if(n[l]<=n[m]){if(t>=n[l]&&t<n[m])r=m-1;else l=m+1;}else{if(t>n[m]&&t<=n[r])l=m+1;else r=m-1;}}return -1;}',
companies:['Amazon','Microsoft'],tags:['Array','Binary Search'],similarQs:['Find Minimum in Rotated Array'],timeComplex:'O(log n)',spaceComplex:'O(1)',pattern:'Modified Binary Search',trick:'Identify which half is sorted first',leetcodeUrl:'https://leetcode.com/problems/search-in-rotated-sorted-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:16,globalOrder:16,title:'Merge Intervals',difficulty:'Medium',
description:'Merge all overlapping intervals.',
examples:[{input:'[[1,3],[2,6],[8,10],[15,18]]',output:'[[1,6],[8,10],[15,18]]'}],
hint:'Sort by start time, then merge overlapping ones.',approach:'Sort intervals. Iterate, merge if current overlaps with last in result.',
java_code:'class Solution{public int[][] merge(int[][] iv){Arrays.sort(iv,(a,b)->a[0]-b[0]);List<int[]> res=new ArrayList<>();for(int[] i:iv){if(res.isEmpty()||res.get(res.size()-1)[1]<i[0])res.add(i);else res.get(res.size()-1)[1]=Math.max(res.get(res.size()-1)[1],i[1]);}return res.toArray(new int[0][]);}}',
python_code:'def merge(iv):\n    iv.sort(key=lambda x:x[0]);res=[]\n    for i in iv:\n        if not res or res[-1][1]<i[0]: res.append(i)\n        else: res[-1][1]=max(res[-1][1],i[1])\n    return res',
cpp_code:'vector<vector<int>> merge(vector<vector<int>>&iv){sort(iv.begin(),iv.end());vector<vector<int>>res;for(auto&i:iv){if(res.empty()||res.back()[1]<i[0])res.push_back(i);else res.back()[1]=max(res.back()[1],i[1]);}return res;}',
companies:['Amazon','Google','Flipkart'],tags:['Array','Sorting','Intervals'],similarQs:['Insert Interval','Meeting Rooms'],timeComplex:'O(nlogn)',spaceComplex:'O(n)',pattern:'Sort + Merge',trick:'Sort first — overlapping intervals become adjacent',leetcodeUrl:'https://leetcode.com/problems/merge-intervals/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:17,globalOrder:17,title:'Rotate Array',difficulty:'Medium',
description:'Rotate the array to the right by k steps.',
examples:[{input:'nums=[1,2,3,4,5,6,7], k=3',output:'[5,6,7,1,2,3,4]'}],
hint:'Reverse whole array, then reverse parts.',approach:'Reverse entire array, then reverse first k and remaining n-k separately.',
java_code:'class Solution{public void rotate(int[] n,int k){k%=n.length;reverse(n,0,n.length-1);reverse(n,0,k-1);reverse(n,k,n.length-1);}void reverse(int[] n,int l,int r){while(l<r){int t=n[l];n[l++]=n[r];n[r--]=t;}}}',
python_code:'def rotate(n,k):\n    k%=len(n)\n    n[:]=n[-k:]+n[:-k]',
cpp_code:'void rotate(vector<int>&n,int k){k%=n.size();reverse(n.begin(),n.end());reverse(n.begin(),n.begin()+k);reverse(n.begin()+k,n.end());}',
companies:['TCS','Amazon'],tags:['Array'],similarQs:['Reverse String'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Reversal Trick',trick:'Triple reversal rotates array in place',leetcodeUrl:'https://leetcode.com/problems/rotate-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:18,globalOrder:18,title:'Majority Element',difficulty:'Easy',
description:'Find the element that appears more than n/2 times.',
examples:[{input:'[2,2,1,1,1,2,2]',output:'2'}],
hint:'Boyer-Moore Voting Algorithm.',approach:'Maintain candidate and count. Increment if same, decrement if different. Reset if count is 0.',
java_code:'class Solution{public int majorityElement(int[] n){int cand=n[0],cnt=0;for(int x:n){if(cnt==0)cand=x;cnt+=(x==cand)?1:-1;}return cand;}}',
python_code:'def majorityElement(n):\n    cand,cnt=None,0\n    for x in n:\n        if cnt==0: cand=x\n        cnt+=1 if x==cand else -1\n    return cand',
cpp_code:'int majorityElement(vector<int>&n){int cand=n[0],cnt=0;for(int x:n){if(cnt==0)cand=x;cnt+=(x==cand)?1:-1;}return cand;}',
companies:['TCS','Amazon'],tags:['Array'],similarQs:['Majority Element II'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Boyer-Moore Voting',trick:'Majority element always survives the cancellation',leetcodeUrl:'https://leetcode.com/problems/majority-element/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:19,globalOrder:19,title:'Set Matrix Zeroes',difficulty:'Medium',
description:'If an element is 0, set its entire row and column to 0. Do it in place.',
examples:[{input:'[[1,1,1],[1,0,1],[1,1,1]]',output:'[[1,0,1],[0,0,0],[1,0,1]]'}],
hint:'Use first row/column as markers.',approach:'Mark zeros in first row and column, then apply, handle first row/col separately.',
java_code:'class Solution{public void setZeroes(int[][] m){boolean fr=false,fc=false;int R=m.length,C=m[0].length;for(int j=0;j<C;j++)if(m[0][j]==0)fr=true;for(int i=0;i<R;i++)if(m[i][0]==0)fc=true;for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][j]==0){m[i][0]=0;m[0][j]=0;}for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][0]==0||m[0][j]==0)m[i][j]=0;if(fr)for(int j=0;j<C;j++)m[0][j]=0;if(fc)for(int i=0;i<R;i++)m[i][0]=0;}}',
python_code:'def setZeroes(m):\n    R,C=len(m),len(m[0]);fr=any(m[0][j]==0 for j in range(C));fc=any(m[i][0]==0 for i in range(R))\n    for i in range(1,R):\n        for j in range(1,C):\n            if m[i][j]==0: m[i][0]=m[0][j]=0\n    for i in range(1,R):\n        for j in range(1,C):\n            if m[i][0]==0 or m[0][j]==0: m[i][j]=0\n    if fr: m[0]=[0]*C\n    if fc:\n        for i in range(R): m[i][0]=0',
cpp_code:'void setZeroes(vector<vector<int>>&m){int R=m.size(),C=m[0].size();bool fr=false,fc=false;for(int j=0;j<C;j++)if(m[0][j]==0)fr=true;for(int i=0;i<R;i++)if(m[i][0]==0)fc=true;for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][j]==0){m[i][0]=0;m[0][j]=0;}for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][0]==0||m[0][j]==0)m[i][j]=0;if(fr)for(int j=0;j<C;j++)m[0][j]=0;if(fc)for(int i=0;i<R;i++)m[i][0]=0;}',
companies:['Amazon','Microsoft'],tags:['Array','Matrix'],similarQs:['Spiral Matrix'],timeComplex:'O(R*C)',spaceComplex:'O(1)',pattern:'In-place Marking',trick:'Use matrix itself as marker storage',leetcodeUrl:'https://leetcode.com/problems/set-matrix-zeroes/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:20,globalOrder:20,title:'Spiral Matrix',difficulty:'Medium',
description:'Return all elements of the matrix in spiral order.',
examples:[{input:'[[1,2,3],[4,5,6],[7,8,9]]',output:'[1,2,3,6,9,8,7,4,5]'}],
hint:'Maintain four boundaries: top, bottom, left, right.',approach:'Traverse right, down, left, up — shrinking boundaries each time.',
java_code:'class Solution{public List<Integer> spiralOrder(int[][] m){List<Integer> res=new ArrayList<>();int top=0,bot=m.length-1,left=0,right=m[0].length-1;while(top<=bot&&left<=right){for(int j=left;j<=right;j++)res.add(m[top][j]);top++;for(int i=top;i<=bot;i++)res.add(m[i][right]);right--;if(top<=bot){for(int j=right;j>=left;j--)res.add(m[bot][j]);bot--;}if(left<=right){for(int i=bot;i>=top;i--)res.add(m[i][left]);left++;}}return res;}}',
python_code:'def spiralOrder(m):\n    res=[];top,bot,left,right=0,len(m)-1,0,len(m[0])-1\n    while top<=bot and left<=right:\n        for j in range(left,right+1): res.append(m[top][j])\n        top+=1\n        for i in range(top,bot+1): res.append(m[i][right])\n        right-=1\n        if top<=bot:\n            for j in range(right,left-1,-1): res.append(m[bot][j])\n            bot-=1\n        if left<=right:\n            for i in range(bot,top-1,-1): res.append(m[i][left])\n            left+=1\n    return res',
cpp_code:'vector<int> spiralOrder(vector<vector<int>>&m){vector<int>res;int top=0,bot=m.size()-1,left=0,right=m[0].size()-1;while(top<=bot&&left<=right){for(int j=left;j<=right;j++)res.push_back(m[top][j]);top++;for(int i=top;i<=bot;i++)res.push_back(m[i][right]);right--;if(top<=bot){for(int j=right;j>=left;j--)res.push_back(m[bot][j]);bot--;}if(left<=right){for(int i=bot;i>=top;i--)res.push_back(m[i][left]);left++;}}return res;}',
companies:['Amazon','Google'],tags:['Array','Matrix'],similarQs:['Set Matrix Zeroes','Spiral Matrix II'],timeComplex:'O(R*C)',spaceComplex:'O(1)',pattern:'Boundary Traversal',trick:'Shrink 4 boundaries each round',leetcodeUrl:'https://leetcode.com/problems/spiral-matrix/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:21,globalOrder:21,title:'Maximum Product Subarray',difficulty:'Medium',
description:'Find contiguous subarray with the largest product.',
examples:[{input:'[2,3,-2,4]',output:'6'}],
hint:'Track both max and min ending here (negatives flip).',approach:'Keep maxEndingHere and minEndingHere, swap when current num is negative.',
java_code:'class Solution{public int maxProduct(int[] n){int max=n[0],mn=n[0],res=n[0];for(int i=1;i<n.length;i++){if(n[i]<0){int t=max;max=mn;mn=t;}max=Math.max(n[i],max*n[i]);mn=Math.min(n[i],mn*n[i]);res=Math.max(res,max);}return res;}}',
python_code:'def maxProduct(n):\n    mx=mn=res=n[0]\n    for x in n[1:]:\n        if x<0: mx,mn=mn,mx\n        mx=max(x,mx*x);mn=min(x,mn*x)\n        res=max(res,mx)\n    return res',
cpp_code:'int maxProduct(vector<int>&n){int mx=n[0],mn=n[0],res=n[0];for(int i=1;i<(int)n.size();i++){if(n[i]<0)swap(mx,mn);mx=max(n[i],mx*n[i]);mn=min(n[i],mn*n[i]);res=max(res,mx);}return res;}',
companies:['Amazon','Microsoft'],tags:['Array','DP'],similarQs:['Maximum Subarray'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:"Kadane's Variant",trick:'Track min too — negative * negative = positive',leetcodeUrl:'https://leetcode.com/problems/maximum-product-subarray/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:22,globalOrder:22,title:'Find All Duplicates in an Array',difficulty:'Medium',
description:'Find all elements that appear twice in an array where 1<=nums[i]<=n.',
examples:[{input:'[4,3,2,7,8,2,3,1]',output:'[2,3]'}],
hint:'Mark visited by negating value at index.',approach:'For each number, go to index abs(num)-1, negate it. If already negative, it is a duplicate.',
java_code:'class Solution{public List<Integer> findDuplicates(int[] n){List<Integer> res=new ArrayList<>();for(int x:n){int idx=Math.abs(x)-1;if(n[idx]<0)res.add(idx+1);else n[idx]=-n[idx];}return res;}}',
python_code:'def findDuplicates(n):\n    res=[]\n    for x in n:\n        idx=abs(x)-1\n        if n[idx]<0: res.append(idx+1)\n        else: n[idx]=-n[idx]\n    return res',
cpp_code:'vector<int> findDuplicates(vector<int>&n){vector<int>res;for(int x:n){int idx=abs(x)-1;if(n[idx]<0)res.push_back(idx+1);else n[idx]=-n[idx];}return res;}',
companies:['Amazon'],tags:['Array'],similarQs:['Find the Duplicate Number'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Index as HashSet',trick:'Use sign bit of value at index as visited flag',leetcodeUrl:'https://leetcode.com/problems/find-all-duplicates-in-an-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:23,globalOrder:23,title:'Subarray Sum Equals K',difficulty:'Medium',
description:'Count the total number of subarrays whose sum equals k.',
examples:[{input:'nums=[1,1,1], k=2',output:'2'}],
hint:'Prefix sum + HashMap of frequencies.',approach:'Track running sum. If (sum-k) seen before, add its frequency to result.',
java_code:'class Solution{public int subarraySum(int[] n,int k){Map<Integer,Integer> m=new HashMap<>();m.put(0,1);int sum=0,cnt=0;for(int x:n){sum+=x;cnt+=m.getOrDefault(sum-k,0);m.merge(sum,1,Integer::sum);}return cnt;}}',
python_code:'def subarraySum(n,k):\n    from collections import defaultdict\n    m=defaultdict(int);m[0]=1;s=cnt=0\n    for x in n:\n        s+=x;cnt+=m[s-k];m[s]+=1\n    return cnt',
cpp_code:'int subarraySum(vector<int>&n,int k){unordered_map<int,int>m;m[0]=1;int s=0,cnt=0;for(int x:n){s+=x;if(m.count(s-k))cnt+=m[s-k];m[s]++;}return cnt;}',
companies:['Amazon','Google'],tags:['Array','Prefix Sum','HashMap'],similarQs:['Continuous Subarray Sum'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'Prefix Sum + HashMap',trick:'sum-k lookup gives count of valid subarrays ending here',leetcodeUrl:'https://leetcode.com/problems/subarray-sum-equals-k/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:24,globalOrder:24,title:'Next Permutation',difficulty:'Medium',
description:'Rearrange numbers into the lexicographically next greater permutation.',
examples:[{input:'[1,2,3]',output:'[1,3,2]'}],
hint:'Find first decreasing element from right, swap with next bigger, reverse suffix.',approach:'Find pivot, find successor, swap, reverse the suffix after pivot.',
java_code:'class Solution{public void nextPermutation(int[] n){int i=n.length-2;while(i>=0&&n[i]>=n[i+1])i--;if(i>=0){int j=n.length-1;while(n[j]<=n[i])j--;int t=n[i];n[i]=n[j];n[j]=t;}int l=i+1,r=n.length-1;while(l<r){int t=n[l];n[l++]=n[r];n[r--]=t;}}}',
python_code:'def nextPermutation(n):\n    i=len(n)-2\n    while i>=0 and n[i]>=n[i+1]: i-=1\n    if i>=0:\n        j=len(n)-1\n        while n[j]<=n[i]: j-=1\n        n[i],n[j]=n[j],n[i]\n    n[i+1:]=reversed(n[i+1:])',
cpp_code:'void nextPermutation(vector<int>&n){int i=n.size()-2;while(i>=0&&n[i]>=n[i+1])i--;if(i>=0){int j=n.size()-1;while(n[j]<=n[i])j--;swap(n[i],n[j]);}reverse(n.begin()+i+1,n.end());}',
companies:['Amazon','Google'],tags:['Array'],similarQs:['Permutations'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'In-place Rearrangement',trick:'Find pivot from right, then reverse suffix',leetcodeUrl:'https://leetcode.com/problems/next-permutation/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:25,globalOrder:25,title:'Minimum Size Subarray Sum',difficulty:'Medium',
description:'Find the minimal length subarray whose sum is greater or equal to target.',
examples:[{input:'target=7, nums=[2,3,1,2,4,3]',output:'2'}],
hint:'Sliding window — expand right, shrink left while sum>=target.',approach:'Two pointer sliding window, track minimum length.',
java_code:'class Solution{public int minSubArrayLen(int t,int[] n){int l=0,sum=0,res=Integer.MAX_VALUE;for(int r=0;r<n.length;r++){sum+=n[r];while(sum>=t){res=Math.min(res,r-l+1);sum-=n[l++];}}return res==Integer.MAX_VALUE?0:res;}}',
python_code:'def minSubArrayLen(t,n):\n    l=s=0;res=float("inf")\n    for r,x in enumerate(n):\n        s+=x\n        while s>=t:\n            res=min(res,r-l+1);s-=n[l];l+=1\n    return res if res!=float("inf") else 0',
cpp_code:'int minSubArrayLen(int t,vector<int>&n){int l=0,s=0,res=INT_MAX;for(int r=0;r<(int)n.size();r++){s+=n[r];while(s>=t){res=min(res,r-l+1);s-=n[l++];}}return res==INT_MAX?0:res;}',
companies:['TCS','Amazon'],tags:['Array','Sliding Window'],similarQs:['Longest Substring Without Repeat'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Sliding Window',trick:'Shrink window aggressively once condition met',leetcodeUrl:'https://leetcode.com/problems/minimum-size-subarray-sum/'},
];

async function seed() {
  await MasterDSAQuestion.deleteMany({});
  const inserted = await MasterDSAQuestion.insertMany(questions);
  console.log(`✅ Inserted ${inserted.length} Master DSA questions`);
  mongoose.disconnect();
}

seed().catch(err => { console.error(err); mongoose.disconnect(); });
