// backend/seedMasterDSA.js
require('dotenv').config();
const mongoose = require('mongoose');
const MasterDSAQuestion = require('./models/MasterDSAQuestion');

mongoose.connect(process.env.MONGO_URI).then(() => console.log('DB connected'));

const questions = [
{topicSlug:'arrays',topic:'Arrays & Strings',order:1,globalOrder:1,title:'Two Sum',difficulty:'Easy',
description:'Given an array of integers nums and an integer target, return indices of two numbers that add up to target.',
examples:[{input:'nums=[2,7,11,15], target=9',output:'[0,1]'}],
hint:'Use HashMap — store complement.',approach:'Single pass HashMap lookup.',
java_code:'class Solution{public int[] twoSum(int[] nums,int target){Map<Integer,Integer> m=new HashMap<>();for(int i=0;i<nums.length;i++){int c=target-nums[i];if(m.containsKey(c))return new int[]{m.get(c),i};m.put(nums[i],i);}return new int[]{};}}',
python_code:'def twoSum(nums,target):\n    seen={}\n    for i,n in enumerate(nums):\n        if target-n in seen: return [seen[target-n],i]\n        seen[n]=i',
cpp_code:'vector<int> twoSum(vector<int>&n,int t){unordered_map<int,int>m;for(int i=0;i<n.size();i++){if(m.count(t-n[i]))return{m[t-n[i]],i};m[n[i]]=i;}return{};}',
companies:['TCS','Amazon'],tags:['Array','HashMap'],similarQs:['Three Sum','4Sum'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'HashMap',trick:'Check before insert',leetcodeUrl:'https://leetcode.com/problems/two-sum/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:2,globalOrder:2,title:'Maximum Subarray',difficulty:'Medium',
description:'Find the contiguous subarray with the largest sum.',
examples:[{input:'[-2,1,-3,4,-1,2,1,-5,4]',output:'6'}],
hint:'Reset sum to 0 if negative.',approach:"Kadane's Algorithm.",
java_code:'class Solution{public int maxSubArray(int[] n){int max=n[0],cur=n[0];for(int i=1;i<n.length;i++){cur=Math.max(n[i],cur+n[i]);max=Math.max(max,cur);}return max;}}',
python_code:'def maxSubArray(n):\n    cur=mx=n[0]\n    for x in n[1:]:\n        cur=max(x,cur+x);mx=max(mx,cur)\n    return mx',
cpp_code:'int maxSubArray(vector<int>&n){int cur=n[0],r=n[0];for(int i=1;i<n.size();i++){cur=max(n[i],cur+n[i]);r=max(r,cur);}return r;}',
companies:['TCS','Infosys'],tags:['Array','DP'],similarQs:['Max Product Subarray'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:"Kadane's",trick:'Restart if cur<0',leetcodeUrl:'https://leetcode.com/problems/maximum-subarray/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:3,globalOrder:3,title:'Best Time to Buy and Sell Stock',difficulty:'Easy',
description:'Find max profit from buying then selling one share.',
examples:[{input:'[7,1,5,3,6,4]',output:'5'}],
hint:'Track min price so far.',approach:'Single pass min tracking.',
java_code:'class Solution{public int maxProfit(int[] p){int mn=Integer.MAX_VALUE,pr=0;for(int x:p){mn=Math.min(mn,x);pr=Math.max(pr,x-mn);}return pr;}}',
python_code:'def maxProfit(p):\n    mn,pr=float("inf"),0\n    for x in p:\n        mn=min(mn,x);pr=max(pr,x-mn)\n    return pr',
cpp_code:'int maxProfit(vector<int>&p){int mn=INT_MAX,r=0;for(int x:p){mn=min(mn,x);r=max(r,x-mn);}return r;}',
companies:['Amazon','TCS'],tags:['Array','Greedy'],similarQs:['Buy Sell II'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Min tracking',trick:'One pass min so far',leetcodeUrl:'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:4,globalOrder:4,title:'Contains Duplicate',difficulty:'Easy',
description:'Return true if any value appears at least twice in the array.',
examples:[{input:'[1,2,3,1]',output:'true'}],
hint:'Use a Set.',approach:'Add to set, if already present return true.',
java_code:'class Solution{public boolean containsDuplicate(int[] n){Set<Integer> s=new HashSet<>();for(int x:n){if(!s.add(x))return true;}return false;}}',
python_code:'def containsDuplicate(n):\n    return len(set(n))!=len(n)',
cpp_code:'bool containsDuplicate(vector<int>&n){unordered_set<int>s;for(int x:n){if(s.count(x))return true;s.insert(x);}return false;}',
companies:['TCS','Wipro'],tags:['Array','HashSet'],similarQs:['Contains Duplicate II'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'Set lookup',trick:'set size vs array size',leetcodeUrl:'https://leetcode.com/problems/contains-duplicate/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:5,globalOrder:5,title:'Product of Array Except Self',difficulty:'Medium',
description:'Return array where output[i] equals product of all elements except nums[i], without division.',
examples:[{input:'[1,2,3,4]',output:'[24,12,8,6]'}],
hint:'Prefix and suffix products.',approach:'Two passes — left products then right products.',
java_code:'class Solution{public int[] productExceptSelf(int[] n){int L=n.length;int[] res=new int[L];res[0]=1;for(int i=1;i<L;i++)res[i]=res[i-1]*n[i-1];int r=1;for(int i=L-1;i>=0;i--){res[i]*=r;r*=n[i];}return res;}}',
python_code:'def productExceptSelf(n):\n    L=len(n);res=[1]*L\n    for i in range(1,L): res[i]=res[i-1]*n[i-1]\n    r=1\n    for i in range(L-1,-1,-1):\n        res[i]*=r;r*=n[i]\n    return res',
cpp_code:'vector<int> productExceptSelf(vector<int>&n){int L=n.size();vector<int>res(L,1);for(int i=1;i<L;i++)res[i]=res[i-1]*n[i-1];int r=1;for(int i=L-1;i>=0;i--){res[i]*=r;r*=n[i];}return res;}',
companies:['Amazon','Flipkart'],tags:['Array','Prefix Sum'],similarQs:['Trapping Rain Water'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Prefix-Suffix',trick:'Output array doubles as prefix array',leetcodeUrl:'https://leetcode.com/problems/product-of-array-except-self/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:6,globalOrder:6,title:'Container With Most Water',difficulty:'Medium',
description:'Given heights array, find two lines that form container with most water.',
examples:[{input:'[1,8,6,2,5,4,8,3,7]',output:'49'}],
hint:'Two pointers from both ends.',approach:'Move pointer with smaller height inward.',
java_code:'class Solution{public int maxArea(int[] h){int l=0,r=h.length-1,max=0;while(l<r){max=Math.max(max,Math.min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}return max;}}',
python_code:'def maxArea(h):\n    l,r,mx=0,len(h)-1,0\n    while l<r:\n        mx=max(mx,min(h[l],h[r])*(r-l))\n        if h[l]<h[r]: l+=1\n        else: r-=1\n    return mx',
cpp_code:'int maxArea(vector<int>&h){int l=0,r=h.size()-1,mx=0;while(l<r){mx=max(mx,min(h[l],h[r])*(r-l));if(h[l]<h[r])l++;else r--;}return mx;}',
companies:['Amazon'],tags:['Array','Two Pointer'],similarQs:['Trapping Rain Water'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two Pointer',trick:'Always move the shorter wall',leetcodeUrl:'https://leetcode.com/problems/container-with-most-water/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:7,globalOrder:7,title:'3Sum',difficulty:'Medium',
description:'Find all unique triplets that sum to zero.',
examples:[{input:'[-1,0,1,2,-1,-4]',output:'[[-1,-1,2],[-1,0,1]]'}],
hint:'Sort then two-pointer for each fixed element.',approach:'Sort array. Fix one element, two-pointer for remaining two.',
java_code:'class Solution{public List<List<Integer>> threeSum(int[] n){Arrays.sort(n);List<List<Integer>> res=new ArrayList<>();for(int i=0;i<n.length-2;i++){if(i>0&&n[i]==n[i-1])continue;int l=i+1,r=n.length-1;while(l<r){int s=n[i]+n[l]+n[r];if(s==0){res.add(Arrays.asList(n[i],n[l],n[r]));while(l<r&&n[l]==n[l+1])l++;while(l<r&&n[r]==n[r-1])r--;l++;r--;}else if(s<0)l++;else r--;}}return res;}}',
python_code:'def threeSum(n):\n    n.sort();res=[]\n    for i in range(len(n)-2):\n        if i>0 and n[i]==n[i-1]: continue\n        l,r=i+1,len(n)-1\n        while l<r:\n            s=n[i]+n[l]+n[r]\n            if s==0:\n                res.append([n[i],n[l],n[r]])\n                while l<r and n[l]==n[l+1]: l+=1\n                while l<r and n[r]==n[r-1]: r-=1\n                l+=1;r-=1\n            elif s<0: l+=1\n            else: r-=1\n    return res',
cpp_code:'vector<vector<int>> threeSum(vector<int>&n){sort(n.begin(),n.end());vector<vector<int>>res;for(int i=0;i<(int)n.size()-2;i++){if(i>0&&n[i]==n[i-1])continue;int l=i+1,r=n.size()-1;while(l<r){int s=n[i]+n[l]+n[r];if(s==0){res.push_back({n[i],n[l],n[r]});while(l<r&&n[l]==n[l+1])l++;while(l<r&&n[r]==n[r-1])r--;l++;r--;}else if(s<0)l++;else r--;}}return res;}',
companies:['Amazon','TCS'],tags:['Array','Two Pointer'],similarQs:['Two Sum','4Sum'],timeComplex:'O(n^2)',spaceComplex:'O(1)',pattern:'Sort + Two Pointer',trick:'Skip duplicates to avoid repeated triplets',leetcodeUrl:'https://leetcode.com/problems/3sum/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:8,globalOrder:8,title:'Sliding Window Maximum',difficulty:'Hard',
description:'Return the max value in each sliding window of size k.',
examples:[{input:'nums=[1,3,-1,-3,5,3,6,7], k=3',output:'[3,3,5,5,6,7]'}],
hint:'Use a deque storing indices, keep it decreasing.',approach:'Monotonic deque — remove smaller elements from back, expired from front.',
java_code:'class Solution{public int[] maxSlidingWindow(int[] n,int k){Deque<Integer> dq=new ArrayDeque<>();int[] res=new int[n.length-k+1];for(int i=0;i<n.length;i++){while(!dq.isEmpty()&&dq.peekFirst()<i-k+1)dq.pollFirst();while(!dq.isEmpty()&&n[dq.peekLast()]<n[i])dq.pollLast();dq.offerLast(i);if(i>=k-1)res[i-k+1]=n[dq.peekFirst()];}return res;}}',
python_code:'from collections import deque\ndef maxSlidingWindow(n,k):\n    dq=deque();res=[]\n    for i,x in enumerate(n):\n        while dq and dq[0]<i-k+1: dq.popleft()\n        while dq and n[dq[-1]]<x: dq.pop()\n        dq.append(i)\n        if i>=k-1: res.append(n[dq[0]])\n    return res',
cpp_code:'vector<int> maxSlidingWindow(vector<int>&n,int k){deque<int>dq;vector<int>res;for(int i=0;i<(int)n.size();i++){while(!dq.empty()&&dq.front()<i-k+1)dq.pop_front();while(!dq.empty()&&n[dq.back()]<n[i])dq.pop_back();dq.push_back(i);if(i>=k-1)res.push_back(n[dq.front()]);}return res;}',
companies:['Google','Amazon'],tags:['Array','Sliding Window','Deque'],similarQs:['Min Window Substring'],timeComplex:'O(n)',spaceComplex:'O(k)',pattern:'Monotonic Deque',trick:'Deque stores indices not values',leetcodeUrl:'https://leetcode.com/problems/sliding-window-maximum/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:9,globalOrder:9,title:'Valid Anagram',difficulty:'Easy',
description:'Given two strings, determine if t is an anagram of s.',
examples:[{input:'s="anagram", t="nagaram"',output:'true'}],
hint:'Count character frequencies.',approach:'Use a frequency array of size 26.',
java_code:'class Solution{public boolean isAnagram(String s,String t){if(s.length()!=t.length())return false;int[] c=new int[26];for(char ch:s.toCharArray())c[ch-\'a\']++;for(char ch:t.toCharArray())c[ch-\'a\']--;for(int x:c)if(x!=0)return false;return true;}}',
python_code:'def isAnagram(s,t):\n    return sorted(s)==sorted(t)',
cpp_code:'bool isAnagram(string s,string t){if(s.size()!=t.size())return false;int c[26]={0};for(char ch:s)c[ch-\'a\']++;for(char ch:t)c[ch-\'a\']--;for(int x:c)if(x)return false;return true;}',
companies:['TCS','Zoho'],tags:['String','HashMap'],similarQs:['Group Anagrams'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Frequency Count',trick:'26-size array beats sorting',leetcodeUrl:'https://leetcode.com/problems/valid-anagram/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:10,globalOrder:10,title:'Group Anagrams',difficulty:'Medium',
description:'Group strings that are anagrams of each other.',
examples:[{input:'["eat","tea","tan","ate","nat","bat"]',output:'[["eat","tea","ate"],["tan","nat"],["bat"]]'}],
hint:'Sort each string as the map key.',approach:'HashMap with sorted-string key, group originals together.',
java_code:'class Solution{public List<List<String>> groupAnagrams(String[] strs){Map<String,List<String>> m=new HashMap<>();for(String s:strs){char[] c=s.toCharArray();Arrays.sort(c);String k=new String(c);m.computeIfAbsent(k,x->new ArrayList<>()).add(s);}return new ArrayList<>(m.values());}}',
python_code:'from collections import defaultdict\ndef groupAnagrams(strs):\n    m=defaultdict(list)\n    for s in strs: m["".join(sorted(s))].append(s)\n    return list(m.values())',
cpp_code:'vector<vector<string>> groupAnagrams(vector<string>&strs){unordered_map<string,vector<string>>m;for(auto&s:strs){string k=s;sort(k.begin(),k.end());m[k].push_back(s);}vector<vector<string>>res;for(auto&p:m)res.push_back(p.second);return res;}',
companies:['Amazon','Flipkart'],tags:['String','HashMap'],similarQs:['Valid Anagram'],timeComplex:'O(n*klogk)',spaceComplex:'O(n*k)',pattern:'HashMap grouping',trick:'Sorted string as canonical key',leetcodeUrl:'https://leetcode.com/problems/group-anagrams/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:11,globalOrder:11,title:'Longest Substring Without Repeating Characters',difficulty:'Medium',
description:'Find length of longest substring without repeating characters.',
examples:[{input:'"abcabcbb"',output:'3'}],
hint:'Sliding window with a set/map.',approach:'Expand right, shrink left when duplicate found.',
java_code:'class Solution{public int lengthOfLongestSubstring(String s){Set<Character> set=new HashSet<>();int l=0,max=0;for(int r=0;r<s.length();r++){while(set.contains(s.charAt(r)))set.remove(s.charAt(l++));set.add(s.charAt(r));max=Math.max(max,r-l+1);}return max;}}',
python_code:'def lengthOfLongestSubstring(s):\n    seen=set();l=mx=0\n    for r,c in enumerate(s):\n        while c in seen:\n            seen.remove(s[l]);l+=1\n        seen.add(c);mx=max(mx,r-l+1)\n    return mx',
cpp_code:'int lengthOfLongestSubstring(string s){unordered_set<char>st;int l=0,mx=0;for(int r=0;r<(int)s.size();r++){while(st.count(s[r])){st.erase(s[l]);l++;}st.insert(s[r]);mx=max(mx,r-l+1);}return mx;}',
companies:['TCS','Wipro','Amazon'],tags:['String','Sliding Window'],similarQs:['Longest Repeating Character Replacement'],timeComplex:'O(n)',spaceComplex:'O(min(n,m))',pattern:'Sliding Window',trick:'Shrink window until valid again',leetcodeUrl:'https://leetcode.com/problems/longest-substring-without-repeating-characters/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:12,globalOrder:12,title:'Longest Common Prefix',difficulty:'Easy',
description:'Find the longest common prefix string amongst an array of strings.',
examples:[{input:'["flower","flow","flight"]',output:'"fl"'}],
hint:'Compare characters column by column.',approach:'Use first string as reference, compare with all others at each index.',
java_code:'class Solution{public String longestCommonPrefix(String[] strs){if(strs.length==0)return "";String pre=strs[0];for(int i=1;i<strs.length;i++){while(!strs[i].startsWith(pre))pre=pre.substring(0,pre.length()-1);}return pre;}}',
python_code:'def longestCommonPrefix(strs):\n    if not strs: return ""\n    pre=strs[0]\n    for s in strs[1:]:\n        while not s.startswith(pre): pre=pre[:-1]\n    return pre',
cpp_code:'string longestCommonPrefix(vector<string>&strs){if(strs.empty())return "";string pre=strs[0];for(int i=1;i<(int)strs.size();i++){while(strs[i].find(pre)!=0)pre=pre.substr(0,pre.size()-1);}return pre;}',
companies:['TCS','Infosys'],tags:['String'],similarQs:['Longest Common Subsequence'],timeComplex:'O(n*m)',spaceComplex:'O(1)',pattern:'Vertical Scanning',trick:'Shrink prefix until it matches',leetcodeUrl:'https://leetcode.com/problems/longest-common-prefix/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:13,globalOrder:13,title:'Move Zeroes',difficulty:'Easy',
description:'Move all zeroes to the end while maintaining relative order of non-zero elements.',
examples:[{input:'[0,1,0,3,12]',output:'[1,3,12,0,0]'}],
hint:'Two pointer — write index for non-zero elements.',approach:'Place non-zero elements forward, fill remaining with zeros.',
java_code:'class Solution{public void moveZeroes(int[] n){int j=0;for(int i=0;i<n.length;i++)if(n[i]!=0)n[j++]=n[i];while(j<n.length)n[j++]=0;}}',
python_code:'def moveZeroes(n):\n    j=0\n    for i in range(len(n)):\n        if n[i]!=0: n[i],n[j]=n[j],n[i];j+=1',
cpp_code:'void moveZeroes(vector<int>&n){int j=0;for(int i=0;i<(int)n.size();i++)if(n[i]!=0)swap(n[j++],n[i]);}',
companies:['Amazon','TCS'],tags:['Array','Two Pointer'],similarQs:['Remove Element'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two Pointer',trick:'Swap instead of overwrite to save writes',leetcodeUrl:'https://leetcode.com/problems/move-zeroes/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:14,globalOrder:14,title:'Find Minimum in Rotated Sorted Array',difficulty:'Medium',
description:'Find the minimum element in a rotated sorted array with no duplicates.',
examples:[{input:'[3,4,5,1,2]',output:'1'}],
hint:'Binary search — compare mid with right.',approach:'If nums[mid]>nums[right], min is in right half, else left half.',
java_code:'class Solution{public int findMin(int[] n){int l=0,r=n.length-1;while(l<r){int m=(l+r)/2;if(n[m]>n[r])l=m+1;else r=m;}return n[l];}}',
python_code:'def findMin(n):\n    l,r=0,len(n)-1\n    while l<r:\n        m=(l+r)//2\n        if n[m]>n[r]: l=m+1\n        else: r=m\n    return n[l]',
cpp_code:'int findMin(vector<int>&n){int l=0,r=n.size()-1;while(l<r){int m=(l+r)/2;if(n[m]>n[r])l=m+1;else r=m;}return n[l];}',
companies:['Amazon','Google'],tags:['Array','Binary Search'],similarQs:['Search in Rotated Array'],timeComplex:'O(log n)',spaceComplex:'O(1)',pattern:'Binary Search Variant',trick:'Compare mid with right end, not left',leetcodeUrl:'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:15,globalOrder:15,title:'Search in Rotated Sorted Array',difficulty:'Medium',
description:'Search target in a rotated sorted array, return index or -1.',
examples:[{input:'nums=[4,5,6,7,0,1,2], target=0',output:'4'}],
hint:'One half is always sorted — check which one.',approach:'Binary search with extra check for sorted half.',
java_code:'class Solution{public int search(int[] n,int t){int l=0,r=n.length-1;while(l<=r){int m=(l+r)/2;if(n[m]==t)return m;if(n[l]<=n[m]){if(t>=n[l]&&t<n[m])r=m-1;else l=m+1;}else{if(t>n[m]&&t<=n[r])l=m+1;else r=m-1;}}return -1;}}',
python_code:'def search(n,t):\n    l,r=0,len(n)-1\n    while l<=r:\n        m=(l+r)//2\n        if n[m]==t: return m\n        if n[l]<=n[m]:\n            if n[l]<=t<n[m]: r=m-1\n            else: l=m+1\n        else:\n            if n[m]<t<=n[r]: l=m+1\n            else: r=m-1\n    return -1',
cpp_code:'int search(vector<int>&n,int t){int l=0,r=n.size()-1;while(l<=r){int m=(l+r)/2;if(n[m]==t)return m;if(n[l]<=n[m]){if(t>=n[l]&&t<n[m])r=m-1;else l=m+1;}else{if(t>n[m]&&t<=n[r])l=m+1;else r=m-1;}}return -1;}',
companies:['Amazon','Microsoft'],tags:['Array','Binary Search'],similarQs:['Find Minimum in Rotated Array'],timeComplex:'O(log n)',spaceComplex:'O(1)',pattern:'Modified Binary Search',trick:'Identify which half is sorted first',leetcodeUrl:'https://leetcode.com/problems/search-in-rotated-sorted-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:16,globalOrder:16,title:'Merge Intervals',difficulty:'Medium',
description:'Merge all overlapping intervals.',
examples:[{input:'[[1,3],[2,6],[8,10],[15,18]]',output:'[[1,6],[8,10],[15,18]]'}],
hint:'Sort by start time, then merge overlapping ones.',approach:'Sort intervals. Iterate, merge if current overlaps with last in result.',
java_code:'class Solution{public int[][] merge(int[][] iv){Arrays.sort(iv,(a,b)->a[0]-b[0]);List<int[]> res=new ArrayList<>();for(int[] i:iv){if(res.isEmpty()||res.get(res.size()-1)[1]<i[0])res.add(i);else res.get(res.size()-1)[1]=Math.max(res.get(res.size()-1)[1],i[1]);}return res.toArray(new int[0][]);}}',
python_code:'def merge(iv):\n    iv.sort(key=lambda x:x[0]);res=[]\n    for i in iv:\n        if not res or res[-1][1]<i[0]: res.append(i)\n        else: res[-1][1]=max(res[-1][1],i[1])\n    return res',
cpp_code:'vector<vector<int>> merge(vector<vector<int>>&iv){sort(iv.begin(),iv.end());vector<vector<int>>res;for(auto&i:iv){if(res.empty()||res.back()[1]<i[0])res.push_back(i);else res.back()[1]=max(res.back()[1],i[1]);}return res;}',
companies:['Amazon','Google','Flipkart'],tags:['Array','Sorting','Intervals'],similarQs:['Insert Interval','Meeting Rooms'],timeComplex:'O(nlogn)',spaceComplex:'O(n)',pattern:'Sort + Merge',trick:'Sort first — overlapping intervals become adjacent',leetcodeUrl:'https://leetcode.com/problems/merge-intervals/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:17,globalOrder:17,title:'Rotate Array',difficulty:'Medium',
description:'Rotate the array to the right by k steps.',
examples:[{input:'nums=[1,2,3,4,5,6,7], k=3',output:'[5,6,7,1,2,3,4]'}],
hint:'Reverse whole array, then reverse parts.',approach:'Reverse entire array, then reverse first k and remaining n-k separately.',
java_code:'class Solution{public void rotate(int[] n,int k){k%=n.length;reverse(n,0,n.length-1);reverse(n,0,k-1);reverse(n,k,n.length-1);}void reverse(int[] n,int l,int r){while(l<r){int t=n[l];n[l++]=n[r];n[r--]=t;}}}',
python_code:'def rotate(n,k):\n    k%=len(n)\n    n[:]=n[-k:]+n[:-k]',
cpp_code:'void rotate(vector<int>&n,int k){k%=n.size();reverse(n.begin(),n.end());reverse(n.begin(),n.begin()+k);reverse(n.begin()+k,n.end());}',
companies:['TCS','Amazon'],tags:['Array'],similarQs:['Reverse String'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Reversal Trick',trick:'Triple reversal rotates array in place',leetcodeUrl:'https://leetcode.com/problems/rotate-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:18,globalOrder:18,title:'Majority Element',difficulty:'Easy',
description:'Find the element that appears more than n/2 times.',
examples:[{input:'[2,2,1,1,1,2,2]',output:'2'}],
hint:'Boyer-Moore Voting Algorithm.',approach:'Maintain candidate and count. Increment if same, decrement if different. Reset if count is 0.',
java_code:'class Solution{public int majorityElement(int[] n){int cand=n[0],cnt=0;for(int x:n){if(cnt==0)cand=x;cnt+=(x==cand)?1:-1;}return cand;}}',
python_code:'def majorityElement(n):\n    cand,cnt=None,0\n    for x in n:\n        if cnt==0: cand=x\n        cnt+=1 if x==cand else -1\n    return cand',
cpp_code:'int majorityElement(vector<int>&n){int cand=n[0],cnt=0;for(int x:n){if(cnt==0)cand=x;cnt+=(x==cand)?1:-1;}return cand;}',
companies:['TCS','Amazon'],tags:['Array'],similarQs:['Majority Element II'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Boyer-Moore Voting',trick:'Majority element always survives the cancellation',leetcodeUrl:'https://leetcode.com/problems/majority-element/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:19,globalOrder:19,title:'Set Matrix Zeroes',difficulty:'Medium',
description:'If an element is 0, set its entire row and column to 0. Do it in place.',
examples:[{input:'[[1,1,1],[1,0,1],[1,1,1]]',output:'[[1,0,1],[0,0,0],[1,0,1]]'}],
hint:'Use first row/column as markers.',approach:'Mark zeros in first row and column, then apply, handle first row/col separately.',
java_code:'class Solution{public void setZeroes(int[][] m){boolean fr=false,fc=false;int R=m.length,C=m[0].length;for(int j=0;j<C;j++)if(m[0][j]==0)fr=true;for(int i=0;i<R;i++)if(m[i][0]==0)fc=true;for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][j]==0){m[i][0]=0;m[0][j]=0;}for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][0]==0||m[0][j]==0)m[i][j]=0;if(fr)for(int j=0;j<C;j++)m[0][j]=0;if(fc)for(int i=0;i<R;i++)m[i][0]=0;}}',
python_code:'def setZeroes(m):\n    R,C=len(m),len(m[0]);fr=any(m[0][j]==0 for j in range(C));fc=any(m[i][0]==0 for i in range(R))\n    for i in range(1,R):\n        for j in range(1,C):\n            if m[i][j]==0: m[i][0]=m[0][j]=0\n    for i in range(1,R):\n        for j in range(1,C):\n            if m[i][0]==0 or m[0][j]==0: m[i][j]=0\n    if fr: m[0]=[0]*C\n    if fc:\n        for i in range(R): m[i][0]=0',
cpp_code:'void setZeroes(vector<vector<int>>&m){int R=m.size(),C=m[0].size();bool fr=false,fc=false;for(int j=0;j<C;j++)if(m[0][j]==0)fr=true;for(int i=0;i<R;i++)if(m[i][0]==0)fc=true;for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][j]==0){m[i][0]=0;m[0][j]=0;}for(int i=1;i<R;i++)for(int j=1;j<C;j++)if(m[i][0]==0||m[0][j]==0)m[i][j]=0;if(fr)for(int j=0;j<C;j++)m[0][j]=0;if(fc)for(int i=0;i<R;i++)m[i][0]=0;}',
companies:['Amazon','Microsoft'],tags:['Array','Matrix'],similarQs:['Spiral Matrix'],timeComplex:'O(R*C)',spaceComplex:'O(1)',pattern:'In-place Marking',trick:'Use matrix itself as marker storage',leetcodeUrl:'https://leetcode.com/problems/set-matrix-zeroes/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:20,globalOrder:20,title:'Spiral Matrix',difficulty:'Medium',
description:'Return all elements of the matrix in spiral order.',
examples:[{input:'[[1,2,3],[4,5,6],[7,8,9]]',output:'[1,2,3,6,9,8,7,4,5]'}],
hint:'Maintain four boundaries: top, bottom, left, right.',approach:'Traverse right, down, left, up — shrinking boundaries each time.',
java_code:'class Solution{public List<Integer> spiralOrder(int[][] m){List<Integer> res=new ArrayList<>();int top=0,bot=m.length-1,left=0,right=m[0].length-1;while(top<=bot&&left<=right){for(int j=left;j<=right;j++)res.add(m[top][j]);top++;for(int i=top;i<=bot;i++)res.add(m[i][right]);right--;if(top<=bot){for(int j=right;j>=left;j--)res.add(m[bot][j]);bot--;}if(left<=right){for(int i=bot;i>=top;i--)res.add(m[i][left]);left++;}}return res;}}',
python_code:'def spiralOrder(m):\n    res=[];top,bot,left,right=0,len(m)-1,0,len(m[0])-1\n    while top<=bot and left<=right:\n        for j in range(left,right+1): res.append(m[top][j])\n        top+=1\n        for i in range(top,bot+1): res.append(m[i][right])\n        right-=1\n        if top<=bot:\n            for j in range(right,left-1,-1): res.append(m[bot][j])\n            bot-=1\n        if left<=right:\n            for i in range(bot,top-1,-1): res.append(m[i][left])\n            left+=1\n    return res',
cpp_code:'vector<int> spiralOrder(vector<vector<int>>&m){vector<int>res;int top=0,bot=m.size()-1,left=0,right=m[0].size()-1;while(top<=bot&&left<=right){for(int j=left;j<=right;j++)res.push_back(m[top][j]);top++;for(int i=top;i<=bot;i++)res.push_back(m[i][right]);right--;if(top<=bot){for(int j=right;j>=left;j--)res.push_back(m[bot][j]);bot--;}if(left<=right){for(int i=bot;i>=top;i--)res.push_back(m[i][left]);left++;}}return res;}',
companies:['Amazon','Google'],tags:['Array','Matrix'],similarQs:['Set Matrix Zeroes','Spiral Matrix II'],timeComplex:'O(R*C)',spaceComplex:'O(1)',pattern:'Boundary Traversal',trick:'Shrink 4 boundaries each round',leetcodeUrl:'https://leetcode.com/problems/spiral-matrix/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:21,globalOrder:21,title:'Maximum Product Subarray',difficulty:'Medium',
description:'Find contiguous subarray with the largest product.',
examples:[{input:'[2,3,-2,4]',output:'6'}],
hint:'Track both max and min ending here (negatives flip).',approach:'Keep maxEndingHere and minEndingHere, swap when current num is negative.',
java_code:'class Solution{public int maxProduct(int[] n){int max=n[0],mn=n[0],res=n[0];for(int i=1;i<n.length;i++){if(n[i]<0){int t=max;max=mn;mn=t;}max=Math.max(n[i],max*n[i]);mn=Math.min(n[i],mn*n[i]);res=Math.max(res,max);}return res;}}',
python_code:'def maxProduct(n):\n    mx=mn=res=n[0]\n    for x in n[1:]:\n        if x<0: mx,mn=mn,mx\n        mx=max(x,mx*x);mn=min(x,mn*x)\n        res=max(res,mx)\n    return res',
cpp_code:'int maxProduct(vector<int>&n){int mx=n[0],mn=n[0],res=n[0];for(int i=1;i<(int)n.size();i++){if(n[i]<0)swap(mx,mn);mx=max(n[i],mx*n[i]);mn=min(n[i],mn*n[i]);res=max(res,mx);}return res;}',
companies:['Amazon','Microsoft'],tags:['Array','DP'],similarQs:['Maximum Subarray'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:"Kadane's Variant",trick:'Track min too — negative * negative = positive',leetcodeUrl:'https://leetcode.com/problems/maximum-product-subarray/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:22,globalOrder:22,title:'Find All Duplicates in an Array',difficulty:'Medium',
description:'Find all elements that appear twice in an array where 1<=nums[i]<=n.',
examples:[{input:'[4,3,2,7,8,2,3,1]',output:'[2,3]'}],
hint:'Mark visited by negating value at index.',approach:'For each number, go to index abs(num)-1, negate it. If already negative, it is a duplicate.',
java_code:'class Solution{public List<Integer> findDuplicates(int[] n){List<Integer> res=new ArrayList<>();for(int x:n){int idx=Math.abs(x)-1;if(n[idx]<0)res.add(idx+1);else n[idx]=-n[idx];}return res;}}',
python_code:'def findDuplicates(n):\n    res=[]\n    for x in n:\n        idx=abs(x)-1\n        if n[idx]<0: res.append(idx+1)\n        else: n[idx]=-n[idx]\n    return res',
cpp_code:'vector<int> findDuplicates(vector<int>&n){vector<int>res;for(int x:n){int idx=abs(x)-1;if(n[idx]<0)res.push_back(idx+1);else n[idx]=-n[idx];}return res;}',
companies:['Amazon'],tags:['Array'],similarQs:['Find the Duplicate Number'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Index as HashSet',trick:'Use sign bit of value at index as visited flag',leetcodeUrl:'https://leetcode.com/problems/find-all-duplicates-in-an-array/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:23,globalOrder:23,title:'Subarray Sum Equals K',difficulty:'Medium',
description:'Count the total number of subarrays whose sum equals k.',
examples:[{input:'nums=[1,1,1], k=2',output:'2'}],
hint:'Prefix sum + HashMap of frequencies.',approach:'Track running sum. If (sum-k) seen before, add its frequency to result.',
java_code:'class Solution{public int subarraySum(int[] n,int k){Map<Integer,Integer> m=new HashMap<>();m.put(0,1);int sum=0,cnt=0;for(int x:n){sum+=x;cnt+=m.getOrDefault(sum-k,0);m.merge(sum,1,Integer::sum);}return cnt;}}',
python_code:'def subarraySum(n,k):\n    from collections import defaultdict\n    m=defaultdict(int);m[0]=1;s=cnt=0\n    for x in n:\n        s+=x;cnt+=m[s-k];m[s]+=1\n    return cnt',
cpp_code:'int subarraySum(vector<int>&n,int k){unordered_map<int,int>m;m[0]=1;int s=0,cnt=0;for(int x:n){s+=x;if(m.count(s-k))cnt+=m[s-k];m[s]++;}return cnt;}',
companies:['Amazon','Google'],tags:['Array','Prefix Sum','HashMap'],similarQs:['Continuous Subarray Sum'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'Prefix Sum + HashMap',trick:'sum-k lookup gives count of valid subarrays ending here',leetcodeUrl:'https://leetcode.com/problems/subarray-sum-equals-k/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:24,globalOrder:24,title:'Next Permutation',difficulty:'Medium',
description:'Rearrange numbers into the lexicographically next greater permutation.',
examples:[{input:'[1,2,3]',output:'[1,3,2]'}],
hint:'Find first decreasing element from right, swap with next bigger, reverse suffix.',approach:'Find pivot, find successor, swap, reverse the suffix after pivot.',
java_code:'class Solution{public void nextPermutation(int[] n){int i=n.length-2;while(i>=0&&n[i]>=n[i+1])i--;if(i>=0){int j=n.length-1;while(n[j]<=n[i])j--;int t=n[i];n[i]=n[j];n[j]=t;}int l=i+1,r=n.length-1;while(l<r){int t=n[l];n[l++]=n[r];n[r--]=t;}}}',
python_code:'def nextPermutation(n):\n    i=len(n)-2\n    while i>=0 and n[i]>=n[i+1]: i-=1\n    if i>=0:\n        j=len(n)-1\n        while n[j]<=n[i]: j-=1\n        n[i],n[j]=n[j],n[i]\n    n[i+1:]=reversed(n[i+1:])',
cpp_code:'void nextPermutation(vector<int>&n){int i=n.size()-2;while(i>=0&&n[i]>=n[i+1])i--;if(i>=0){int j=n.size()-1;while(n[j]<=n[i])j--;swap(n[i],n[j]);}reverse(n.begin()+i+1,n.end());}',
companies:['Amazon','Google'],tags:['Array'],similarQs:['Permutations'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'In-place Rearrangement',trick:'Find pivot from right, then reverse suffix',leetcodeUrl:'https://leetcode.com/problems/next-permutation/'},

{topicSlug:'arrays',topic:'Arrays & Strings',order:25,globalOrder:25,title:'Minimum Size Subarray Sum',difficulty:'Medium',
description:'Find the minimal length subarray whose sum is greater or equal to target.',
examples:[{input:'target=7, nums=[2,3,1,2,4,3]',output:'2'}],
hint:'Sliding window — expand right, shrink left while sum>=target.',approach:'Two pointer sliding window, track minimum length.',
java_code:'class Solution{public int minSubArrayLen(int t,int[] n){int l=0,sum=0,res=Integer.MAX_VALUE;for(int r=0;r<n.length;r++){sum+=n[r];while(sum>=t){res=Math.min(res,r-l+1);sum-=n[l++];}}return res==Integer.MAX_VALUE?0:res;}}',
python_code:'def minSubArrayLen(t,n):\n    l=s=0;res=float("inf")\n    for r,x in enumerate(n):\n        s+=x\n        while s>=t:\n            res=min(res,r-l+1);s-=n[l];l+=1\n    return res if res!=float("inf") else 0',
cpp_code:'int minSubArrayLen(int t,vector<int>&n){int l=0,s=0,res=INT_MAX;for(int r=0;r<(int)n.size();r++){s+=n[r];while(s>=t){res=min(res,r-l+1);s-=n[l++];}}return res==INT_MAX?0:res;}',
companies:['TCS','Amazon'],tags:['Array','Sliding Window'],similarQs:['Longest Substring Without Repeat'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Sliding Window',trick:'Shrink window aggressively once condition met',leetcodeUrl:'https://leetcode.com/problems/minimum-size-subarray-sum/'},

{topicSlug:'linkedlist',topic:'Linked List',order:1,globalOrder:41,title:'Reverse Linked List',difficulty:'Easy',
description:'Given the head of a singly linked list, reverse the list and return the new head.',
examples:[{input:'head=[1,2,3,4,5]',output:'[5,4,3,2,1]'}],
hint:'Use three pointers: prev, curr, next.',approach:'Iteratively reverse the next pointer of each node.',
java_code:'class Solution{public ListNode reverseList(ListNode head){ListNode prev=null,curr=head;while(curr!=null){ListNode next=curr.next;curr.next=prev;prev=curr;curr=next;}return prev;}}',
python_code:'def reverseList(head):\n    prev=None\n    while head:\n        nxt=head.next;head.next=prev;prev=head;head=nxt\n    return prev',
cpp_code:'ListNode* reverseList(ListNode* head){ListNode* prev=nullptr;while(head){auto nxt=head->next;head->next=prev;prev=head;head=nxt;}return prev;}',
companies:['TCS','Infosys','Amazon'],tags:['LinkedList'],similarQs:['Reverse Nodes in k-Group'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Pointer reversal',trick:'prev/curr/next dance',leetcodeUrl:'https://leetcode.com/problems/reverse-linked-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:2,globalOrder:42,title:'Detect Cycle in Linked List',difficulty:'Easy',
description:'Determine if the linked list has a cycle.',
examples:[{input:'head=[3,2,0,-4], pos=1',output:'true'}],
hint:"Floyd's algorithm — slow/fast pointers.",approach:'Slow moves 1, fast moves 2. If they meet, cycle exists.',
java_code:'class Solution{public boolean hasCycle(ListNode head){ListNode slow=head,fast=head;while(fast!=null&&fast.next!=null){slow=slow.next;fast=fast.next.next;if(slow==fast)return true;}return false;}}',
python_code:'def hasCycle(head):\n    slow=fast=head\n    while fast and fast.next:\n        slow=slow.next;fast=fast.next.next\n        if slow==fast: return True\n    return False',
cpp_code:'bool hasCycle(ListNode* head){auto s=head,f=head;while(f&&f->next){s=s->next;f=f->next->next;if(s==f)return true;}return false;}',
companies:['Amazon','TCS'],tags:['LinkedList','Two Pointer'],similarQs:['Find Cycle Start'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Fast-Slow Pointer',trick:'Fast catches slow inside cycle',leetcodeUrl:'https://leetcode.com/problems/linked-list-cycle/'},

{topicSlug:'linkedlist',topic:'Linked List',order:3,globalOrder:43,title:'Merge Two Sorted Lists',difficulty:'Easy',
description:'Merge two sorted linked lists into one sorted list.',
examples:[{input:'l1=[1,2,4], l2=[1,3,4]',output:'[1,1,2,3,4,4]'}],
hint:'Use a dummy node, compare heads.',approach:'Build new list by always picking smaller head.',
java_code:'class Solution{public ListNode mergeTwoLists(ListNode a,ListNode b){ListNode dummy=new ListNode(0),cur=dummy;while(a!=null&&b!=null){if(a.val<=b.val){cur.next=a;a=a.next;}else{cur.next=b;b=b.next;}cur=cur.next;}cur.next=(a!=null)?a:b;return dummy.next;}}',
python_code:'def mergeTwoLists(a,b):\n    dummy=cur=ListNode(0)\n    while a and b:\n        if a.val<=b.val: cur.next=a;a=a.next\n        else: cur.next=b;b=b.next\n        cur=cur.next\n    cur.next=a or b\n    return dummy.next',
cpp_code:'ListNode* mergeTwoLists(ListNode* a,ListNode* b){ListNode dummy(0);auto cur=&dummy;while(a&&b){if(a->val<=b->val){cur->next=a;a=a->next;}else{cur->next=b;b=b->next;}cur=cur->next;}cur->next=a?a:b;return dummy.next;}',
companies:['Amazon','TCS'],tags:['LinkedList'],similarQs:['Merge k Sorted Lists'],timeComplex:'O(n+m)',spaceComplex:'O(1)',pattern:'Dummy node merge',trick:'Dummy node avoids edge-case head handling',leetcodeUrl:'https://leetcode.com/problems/merge-two-sorted-lists/'},

{topicSlug:'linkedlist',topic:'Linked List',order:4,globalOrder:44,title:'Remove Nth Node From End of List',difficulty:'Medium',
description:'Remove the nth node from the end and return head.',
examples:[{input:'head=[1,2,3,4,5], n=2',output:'[1,2,3,5]'}],
hint:'Two pointers, gap of n.',approach:'Move fast n steps ahead, then move both till fast hits end.',
java_code:'class Solution{public ListNode removeNthFromEnd(ListNode head,int n){ListNode dummy=new ListNode(0);dummy.next=head;ListNode slow=dummy,fast=dummy;for(int i=0;i<n;i++)fast=fast.next;while(fast.next!=null){slow=slow.next;fast=fast.next;}slow.next=slow.next.next;return dummy.next;}}',
python_code:'def removeNthFromEnd(head,n):\n    dummy=ListNode(0);dummy.next=head;slow=fast=dummy\n    for _ in range(n): fast=fast.next\n    while fast.next:\n        slow=slow.next;fast=fast.next\n    slow.next=slow.next.next\n    return dummy.next',
cpp_code:'ListNode* removeNthFromEnd(ListNode* head,int n){ListNode dummy(0);dummy.next=head;auto slow=&dummy,fast=&dummy;for(int i=0;i<n;i++)fast=fast->next;while(fast->next){slow=slow->next;fast=fast->next;}slow->next=slow->next->next;return dummy.next;}',
companies:['Amazon','Microsoft'],tags:['LinkedList','Two Pointer'],similarQs:['Middle of Linked List'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two Pointer Gap',trick:'Dummy node handles removing head edge case',leetcodeUrl:'https://leetcode.com/problems/remove-nth-node-from-end-of-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:5,globalOrder:45,title:'Linked List Cycle II (Find Start)',difficulty:'Medium',
description:'Return the node where the cycle begins, or null if no cycle.',
examples:[{input:'head=[3,2,0,-4], pos=1',output:'Node at index 1'}],
hint:"After slow/fast meet, reset one pointer to head.",approach:"Floyd's algorithm: after detecting meeting point, move one pointer to head, advance both by 1 until they meet again — that's the cycle start.",
java_code:'class Solution{public ListNode detectCycle(ListNode head){ListNode slow=head,fast=head;while(fast!=null&&fast.next!=null){slow=slow.next;fast=fast.next.next;if(slow==fast){ListNode p=head;while(p!=slow){p=p.next;slow=slow.next;}return p;}}return null;}}',
python_code:'def detectCycle(head):\n    slow=fast=head\n    while fast and fast.next:\n        slow=slow.next;fast=fast.next.next\n        if slow==fast:\n            p=head\n            while p!=slow:\n                p=p.next;slow=slow.next\n            return p\n    return None',
cpp_code:'ListNode* detectCycle(ListNode* head){auto slow=head,fast=head;while(fast&&fast->next){slow=slow->next;fast=fast->next->next;if(slow==fast){auto p=head;while(p!=slow){p=p->next;slow=slow->next;}return p;}}return nullptr;}',
companies:['Amazon','Google'],tags:['LinkedList','Two Pointer'],similarQs:['Linked List Cycle'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:"Floyd's Cycle Detection",trick:'Distance from head to cycle start = distance from meeting point to start',leetcodeUrl:'https://leetcode.com/problems/linked-list-cycle-ii/'},

{topicSlug:'linkedlist',topic:'Linked List',order:6,globalOrder:46,title:'Palindrome Linked List',difficulty:'Easy',
description:'Check if a singly linked list is a palindrome.',
examples:[{input:'head=[1,2,2,1]',output:'true'}],
hint:'Find middle, reverse second half, compare.',approach:'Use slow/fast to find middle, reverse second half, then compare both halves.',
java_code:'class Solution{public boolean isPalindrome(ListNode head){ListNode slow=head,fast=head;while(fast!=null&&fast.next!=null){slow=slow.next;fast=fast.next.next;}ListNode prev=null;while(slow!=null){ListNode nxt=slow.next;slow.next=prev;prev=slow;slow=nxt;}ListNode p1=head,p2=prev;while(p2!=null){if(p1.val!=p2.val)return false;p1=p1.next;p2=p2.next;}return true;}}',
python_code:'def isPalindrome(head):\n    vals=[]\n    while head: vals.append(head.val);head=head.next\n    return vals==vals[::-1]',
cpp_code:'bool isPalindrome(ListNode* head){vector<int>v;while(head){v.push_back(head->val);head=head->next;}int l=0,r=v.size()-1;while(l<r){if(v[l]!=v[r])return false;l++;r--;}return true;}',
companies:['TCS','Amazon'],tags:['LinkedList','Two Pointer'],similarQs:['Reverse Linked List'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Reverse half + compare',trick:'Reversing second half avoids extra array in optimal solution',leetcodeUrl:'https://leetcode.com/problems/palindrome-linked-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:7,globalOrder:47,title:'Add Two Numbers',difficulty:'Medium',
description:'Add two numbers represented as linked lists (digits in reverse order).',
examples:[{input:'l1=[2,4,3], l2=[5,6,4]',output:'[7,0,8]'}],
hint:'Simulate addition with carry.',approach:'Traverse both lists simultaneously, add digits + carry, build result list.',
java_code:'class Solution{public ListNode addTwoNumbers(ListNode l1,ListNode l2){ListNode dummy=new ListNode(0),cur=dummy;int carry=0;while(l1!=null||l2!=null||carry!=0){int sum=carry+(l1!=null?l1.val:0)+(l2!=null?l2.val:0);carry=sum/10;cur.next=new ListNode(sum%10);cur=cur.next;if(l1!=null)l1=l1.next;if(l2!=null)l2=l2.next;}return dummy.next;}}',
python_code:'def addTwoNumbers(l1,l2):\n    dummy=cur=ListNode(0);carry=0\n    while l1 or l2 or carry:\n        s=carry+(l1.val if l1 else 0)+(l2.val if l2 else 0)\n        carry=s//10;cur.next=ListNode(s%10);cur=cur.next\n        l1=l1.next if l1 else None\n        l2=l2.next if l2 else None\n    return dummy.next',
cpp_code:'ListNode* addTwoNumbers(ListNode* l1,ListNode* l2){ListNode dummy(0);auto cur=&dummy;int carry=0;while(l1||l2||carry){int s=carry+(l1?l1->val:0)+(l2?l2->val:0);carry=s/10;cur->next=new ListNode(s%10);cur=cur->next;if(l1)l1=l1->next;if(l2)l2=l2->next;}return dummy.next;}',
companies:['Amazon','Microsoft'],tags:['LinkedList','Math'],similarQs:['Multiply Two Numbers'],timeComplex:'O(max(n,m))',spaceComplex:'O(max(n,m))',pattern:'Simulation with carry',trick:'Handle final carry by continuing loop while carry!=0',leetcodeUrl:'https://leetcode.com/problems/add-two-numbers/'},

{topicSlug:'linkedlist',topic:'Linked List',order:8,globalOrder:48,title:'Intersection of Two Linked Lists',difficulty:'Easy',
description:'Find the node where two linked lists intersect.',
examples:[{input:'listA, listB sharing tail',output:'Intersection node'}],
hint:'Two pointers, switch to other list at end.',approach:'When pointer reaches end of its list, redirect to head of other list. They will meet at intersection.',
java_code:'class Solution{public ListNode getIntersectionNode(ListNode a,ListNode b){ListNode p1=a,p2=b;while(p1!=p2){p1=(p1==null)?b:p1.next;p2=(p2==null)?a:p2.next;}return p1;}}',
python_code:'def getIntersectionNode(a,b):\n    p1,p2=a,b\n    while p1!=p2:\n        p1=b if p1 is None else p1.next\n        p2=a if p2 is None else p2.next\n    return p1',
cpp_code:'ListNode* getIntersectionNode(ListNode* a,ListNode* b){auto p1=a,p2=b;while(p1!=p2){p1=p1?p1->next:b;p2=p2?p2->next:a;}return p1;}',
companies:['Amazon','Google'],tags:['LinkedList','Two Pointer'],similarQs:['Linked List Cycle'],timeComplex:'O(n+m)',spaceComplex:'O(1)',pattern:'Two pointer switch',trick:'Switching lists equalizes the remaining distance',leetcodeUrl:'https://leetcode.com/problems/intersection-of-two-linked-lists/'},

{topicSlug:'linkedlist',topic:'Linked List',order:9,globalOrder:49,title:'Remove Duplicates from Sorted List',difficulty:'Easy',
description:'Remove duplicates from a sorted linked list so each element appears once.',
examples:[{input:'head=[1,1,2,3,3]',output:'[1,2,3]'}],
hint:'Compare current with next, skip if same.',approach:'Single pass: if curr.val==curr.next.val, skip next, else move forward.',
java_code:'class Solution{public ListNode deleteDuplicates(ListNode head){ListNode cur=head;while(cur!=null&&cur.next!=null){if(cur.val==cur.next.val)cur.next=cur.next.next;else cur=cur.next;}return head;}}',
python_code:'def deleteDuplicates(head):\n    cur=head\n    while cur and cur.next:\n        if cur.val==cur.next.val: cur.next=cur.next.next\n        else: cur=cur.next\n    return head',
cpp_code:'ListNode* deleteDuplicates(ListNode* head){auto cur=head;while(cur&&cur->next){if(cur->val==cur->next->val)cur->next=cur->next->next;else cur=cur->next;}return head;}',
companies:['TCS','Infosys'],tags:['LinkedList'],similarQs:['Remove Duplicates II'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Single pass skip',trick:'Sorted list means duplicates are always adjacent',leetcodeUrl:'https://leetcode.com/problems/remove-duplicates-from-sorted-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:10,globalOrder:50,title:'Middle of the Linked List',difficulty:'Easy',
description:'Return the middle node of a linked list.',
examples:[{input:'head=[1,2,3,4,5]',output:'Node 3'}],
hint:'Slow/fast pointer.',approach:'Fast moves 2 steps, slow moves 1. When fast reaches end, slow is at middle.',
java_code:'class Solution{public ListNode middleNode(ListNode head){ListNode slow=head,fast=head;while(fast!=null&&fast.next!=null){slow=slow.next;fast=fast.next.next;}return slow;}}',
python_code:'def middleNode(head):\n    slow=fast=head\n    while fast and fast.next:\n        slow=slow.next;fast=fast.next.next\n    return slow',
cpp_code:'ListNode* middleNode(ListNode* head){auto slow=head,fast=head;while(fast&&fast->next){slow=slow->next;fast=fast->next->next;}return slow;}',
companies:['Amazon','TCS'],tags:['LinkedList','Two Pointer'],similarQs:['Remove Nth Node From End'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Fast-Slow Pointer',trick:'Fast moves twice as fast as slow',leetcodeUrl:'https://leetcode.com/problems/middle-of-the-linked-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:11,globalOrder:51,title:'Reverse Linked List II',difficulty:'Medium',
description:'Reverse nodes from position left to right in a linked list.',
examples:[{input:'head=[1,2,3,4,5], left=2, right=4',output:'[1,4,3,2,5]'}],
hint:'Find node before left, reverse the sublist, reconnect.',approach:'Move to (left-1)th node, reverse next (right-left+1) nodes, reconnect pointers.',
java_code:'class Solution{public ListNode reverseBetween(ListNode head,int left,int right){ListNode dummy=new ListNode(0);dummy.next=head;ListNode prev=dummy;for(int i=0;i<left-1;i++)prev=prev.next;ListNode curr=prev.next;for(int i=0;i<right-left;i++){ListNode nxt=curr.next;curr.next=nxt.next;nxt.next=prev.next;prev.next=nxt;}return dummy.next;}}',
python_code:'def reverseBetween(head,left,right):\n    dummy=ListNode(0);dummy.next=head;prev=dummy\n    for _ in range(left-1): prev=prev.next\n    curr=prev.next\n    for _ in range(right-left):\n        nxt=curr.next;curr.next=nxt.next;nxt.next=prev.next;prev.next=nxt\n    return dummy.next',
cpp_code:'ListNode* reverseBetween(ListNode* head,int left,int right){ListNode dummy(0);dummy.next=head;auto prev=&dummy;for(int i=0;i<left-1;i++)prev=prev->next;auto curr=prev->next;for(int i=0;i<right-left;i++){auto nxt=curr->next;curr->next=nxt->next;nxt->next=prev->next;prev->next=nxt;}return dummy.next;}',
companies:['Amazon','Microsoft'],tags:['LinkedList'],similarQs:['Reverse Linked List'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Partial reversal',trick:'Insert nxt right after prev repeatedly',leetcodeUrl:'https://leetcode.com/problems/reverse-linked-list-ii/'},

{topicSlug:'linkedlist',topic:'Linked List',order:12,globalOrder:52,title:'Swap Nodes in Pairs',difficulty:'Medium',
description:'Swap every two adjacent nodes in a linked list.',
examples:[{input:'head=[1,2,3,4]',output:'[2,1,4,3]'}],
hint:'Use dummy node, swap pairs iteratively.',approach:'For each pair, rewire pointers: prev->second->first->next pair.',
java_code:'class Solution{public ListNode swapPairs(ListNode head){ListNode dummy=new ListNode(0);dummy.next=head;ListNode prev=dummy;while(prev.next!=null&&prev.next.next!=null){ListNode first=prev.next,second=first.next;first.next=second.next;second.next=first;prev.next=second;prev=first;}return dummy.next;}}',
python_code:'def swapPairs(head):\n    dummy=ListNode(0);dummy.next=head;prev=dummy\n    while prev.next and prev.next.next:\n        first=prev.next;second=first.next\n        first.next=second.next;second.next=first;prev.next=second\n        prev=first\n    return dummy.next',
cpp_code:'ListNode* swapPairs(ListNode* head){ListNode dummy(0);dummy.next=head;auto prev=&dummy;while(prev->next&&prev->next->next){auto first=prev->next,second=first->next;first->next=second->next;second->next=first;prev->next=second;prev=first;}return dummy.next;}',
companies:['Amazon','TCS'],tags:['LinkedList'],similarQs:['Reverse Nodes in k-Group'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Pairwise pointer rewire',trick:'Track prev to reconnect after each swap',leetcodeUrl:'https://leetcode.com/problems/swap-nodes-in-pairs/'},

{topicSlug:'linkedlist',topic:'Linked List',order:13,globalOrder:53,title:'Reverse Nodes in k-Group',difficulty:'Hard',
description:'Reverse nodes of a linked list k at a time.',
examples:[{input:'head=[1,2,3,4,5], k=2',output:'[2,1,4,3,5]'}],
hint:'Reverse first k nodes, recursively handle rest.',approach:'Check if k nodes exist, reverse them, recursively connect to reversed remainder.',
java_code:'class Solution{public ListNode reverseKGroup(ListNode head,int k){ListNode node=head;int count=0;while(node!=null&&count<k){node=node.next;count++;}if(count<k)return head;ListNode prev=reverseKGroup(node,k);ListNode curr=head;while(count-->0){ListNode nxt=curr.next;curr.next=prev;prev=curr;curr=nxt;}return prev;}}',
python_code:'def reverseKGroup(head,k):\n    node=head;count=0\n    while node and count<k: node=node.next;count+=1\n    if count<k: return head\n    prev=reverseKGroup(node,k);curr=head\n    while count>0:\n        nxt=curr.next;curr.next=prev;prev=curr;curr=nxt;count-=1\n    return prev',
cpp_code:'ListNode* reverseKGroup(ListNode* head,int k){auto node=head;int count=0;while(node&&count<k){node=node->next;count++;}if(count<k)return head;auto prev=reverseKGroup(node,k);auto curr=head;while(count-->0){auto nxt=curr->next;curr->next=prev;prev=curr;curr=nxt;}return prev;}',
companies:['Amazon','Google'],tags:['LinkedList','Recursion'],similarQs:['Swap Nodes in Pairs'],timeComplex:'O(n)',spaceComplex:'O(n/k)',pattern:'Recursive group reversal',trick:'Recursion handles remaining groups automatically',leetcodeUrl:'https://leetcode.com/problems/reverse-nodes-in-k-group/'},

{topicSlug:'linkedlist',topic:'Linked List',order:14,globalOrder:54,title:'Rotate List',difficulty:'Medium',
description:'Rotate the list to the right by k places.',
examples:[{input:'head=[1,2,3,4,5], k=2',output:'[4,5,1,2,3]'}],
hint:'Make it circular, find new break point.',approach:'Find length, connect tail to head making circle, break at (len-k%len)th node.',
java_code:'class Solution{public ListNode rotateRight(ListNode head,int k){if(head==null)return null;int len=1;ListNode tail=head;while(tail.next!=null){tail=tail.next;len++;}k%=len;if(k==0)return head;tail.next=head;ListNode newTail=head;for(int i=0;i<len-k-1;i++)newTail=newTail.next;ListNode newHead=newTail.next;newTail.next=null;return newHead;}}',
python_code:'def rotateRight(head,k):\n    if not head: return None\n    length=1;tail=head\n    while tail.next: tail=tail.next;length+=1\n    k%=length\n    if k==0: return head\n    tail.next=head;newTail=head\n    for _ in range(length-k-1): newTail=newTail.next\n    newHead=newTail.next;newTail.next=None\n    return newHead',
cpp_code:'ListNode* rotateRight(ListNode* head,int k){if(!head)return nullptr;int len=1;auto tail=head;while(tail->next){tail=tail->next;len++;}k%=len;if(k==0)return head;tail->next=head;auto newTail=head;for(int i=0;i<len-k-1;i++)newTail=newTail->next;auto newHead=newTail->next;newTail->next=nullptr;return newHead;}',
companies:['Amazon','Microsoft'],tags:['LinkedList'],similarQs:['Rotate Array'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Circular list trick',trick:'k%length avoids redundant full rotations',leetcodeUrl:'https://leetcode.com/problems/rotate-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:15,globalOrder:55,title:'Copy List with Random Pointer',difficulty:'Medium',
description:'Deep copy a linked list with an extra random pointer per node.',
examples:[{input:'head=[[7,null],[13,0],[11,4],[10,2],[1,0]]',output:'Deep copy with same structure'}],
hint:'Use a HashMap from old node to new node.',approach:'First pass: create copy nodes, map old->new. Second pass: set next and random pointers using map.',
java_code:'class Solution{public Node copyRandomList(Node head){if(head==null)return null;Map<Node,Node> map=new HashMap<>();Node cur=head;while(cur!=null){map.put(cur,new Node(cur.val));cur=cur.next;}cur=head;while(cur!=null){map.get(cur).next=map.get(cur.next);map.get(cur).random=map.get(cur.random);cur=cur.next;}return map.get(head);}}',
python_code:'def copyRandomList(head):\n    if not head: return None\n    m={}\n    cur=head\n    while cur:\n        m[cur]=Node(cur.val);cur=cur.next\n    cur=head\n    while cur:\n        m[cur].next=m.get(cur.next)\n        m[cur].random=m.get(cur.random)\n        cur=cur.next\n    return m[head]',
cpp_code:'Node* copyRandomList(Node* head){if(!head)return nullptr;unordered_map<Node*,Node*>m;auto cur=head;while(cur){m[cur]=new Node(cur->val);cur=cur->next;}cur=head;while(cur){m[cur]->next=m[cur->next];m[cur]->random=m[cur->random];cur=cur->next;}return m[head];}',
companies:['Amazon','Google'],tags:['LinkedList','HashMap'],similarQs:['Clone Graph'],timeComplex:'O(n)',spaceComplex:'O(n)',pattern:'HashMap node mapping',trick:'Two-pass: create nodes first, link pointers second',leetcodeUrl:'https://leetcode.com/problems/copy-list-with-random-pointer/'},

{topicSlug:'linkedlist',topic:'Linked List',order:16,globalOrder:56,title:'LRU Cache',difficulty:'Medium',
description:'Design an LRU (Least Recently Used) cache with get and put in O(1).',
examples:[{input:'LRUCache(2); put(1,1); put(2,2); get(1)',output:'1'}],
hint:'HashMap + Doubly Linked List.',approach:'Doubly linked list maintains order, HashMap gives O(1) node access. Move accessed node to front.',
java_code:'class LRUCache{class Node{int k,v;Node prev,next;Node(int k,int v){this.k=k;this.v=v;}}int cap;Map<Integer,Node> map=new HashMap<>();Node head=new Node(0,0),tail=new Node(0,0);public LRUCache(int capacity){cap=capacity;head.next=tail;tail.prev=head;}void remove(Node n){n.prev.next=n.next;n.next.prev=n.prev;}void insert(Node n){n.next=head.next;n.prev=head;head.next.prev=n;head.next=n;}public int get(int key){if(!map.containsKey(key))return -1;Node n=map.get(key);remove(n);insert(n);return n.v;}public void put(int key,int value){if(map.containsKey(key))remove(map.get(key));if(map.size()==cap){map.remove(tail.prev.k);remove(tail.prev);}Node n=new Node(key,value);map.put(key,n);insert(n);}}',
python_code:'class LRUCache:\n    def __init__(self,capacity):\n        from collections import OrderedDict\n        self.cap=capacity;self.cache=OrderedDict()\n    def get(self,key):\n        if key not in self.cache: return -1\n        self.cache.move_to_end(key)\n        return self.cache[key]\n    def put(self,key,value):\n        if key in self.cache: self.cache.move_to_end(key)\n        self.cache[key]=value\n        if len(self.cache)>self.cap: self.cache.popitem(last=False)',
cpp_code:'class LRUCache{list<pair<int,int>> dl;unordered_map<int,list<pair<int,int>>::iterator> mp;int cap;public:LRUCache(int c){cap=c;}int get(int key){if(mp.find(key)==mp.end())return -1;dl.splice(dl.begin(),dl,mp[key]);mp[key]=dl.begin();return dl.begin()->second;}void put(int key,int value){if(mp.find(key)!=mp.end())dl.erase(mp[key]);dl.push_front({key,value});mp[key]=dl.begin();if((int)mp.size()>cap){auto last=dl.back();mp.erase(last.first);dl.pop_back();}}};',
companies:['Amazon','Flipkart','Microsoft'],tags:['LinkedList','Design','HashMap'],similarQs:['LFU Cache'],timeComplex:'O(1)',spaceComplex:'O(capacity)',pattern:'HashMap + DLL',trick:'Doubly linked list gives O(1) removal from any position',leetcodeUrl:'https://leetcode.com/problems/lru-cache/'},

{topicSlug:'linkedlist',topic:'Linked List',order:17,globalOrder:57,title:'Flatten a Multilevel Doubly Linked List',difficulty:'Medium',
description:'Flatten a multilevel doubly linked list into a single-level list.',
examples:[{input:'Multilevel list with child pointers',output:'Flattened single list'}],
hint:'DFS — when child exists, recursively flatten it first.',approach:'Use a stack or recursion: when node has child, flatten child, insert between node and node.next.',
java_code:'class Solution{public Node flatten(Node head){Node cur=head;while(cur!=null){if(cur.child!=null){Node next=cur.next;Node childHead=flatten(cur.child);cur.next=childHead;childHead.prev=cur;cur.child=null;Node tail=childHead;while(tail.next!=null)tail=tail.next;tail.next=next;if(next!=null)next.prev=tail;}cur=cur.next;}return head;}}',
python_code:'def flatten(head):\n    cur=head\n    while cur:\n        if cur.child:\n            nxt=cur.next\n            childHead=flatten(cur.child)\n            cur.next=childHead;childHead.prev=cur;cur.child=None\n            tail=childHead\n            while tail.next: tail=tail.next\n            tail.next=nxt\n            if nxt: nxt.prev=tail\n        cur=cur.next\n    return head',
cpp_code:'Node* flatten(Node* head){auto cur=head;while(cur){if(cur->child){auto nxt=cur->next;auto childHead=flatten(cur->child);cur->next=childHead;childHead->prev=cur;cur->child=nullptr;auto tail=childHead;while(tail->next)tail=tail->next;tail->next=nxt;if(nxt)nxt->prev=tail;}cur=cur->next;}return head;}',
companies:['Amazon'],tags:['LinkedList','Recursion'],similarQs:['Flatten Binary Tree to Linked List'],timeComplex:'O(n)',spaceComplex:'O(d)',pattern:'Recursive flatten',trick:'Process child before moving past current node',leetcodeUrl:'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:18,globalOrder:58,title:'Odd Even Linked List',difficulty:'Medium',
description:'Group all odd-indexed nodes together followed by even-indexed nodes.',
examples:[{input:'head=[1,2,3,4,5]',output:'[1,3,5,2,4]'}],
hint:'Two pointers for odd and even chains.',approach:'Maintain separate odd and even pointers, link odd chain end to even chain head.',
java_code:'class Solution{public ListNode oddEvenList(ListNode head){if(head==null||head.next==null)return head;ListNode odd=head,even=head.next,evenHead=even;while(even!=null&&even.next!=null){odd.next=even.next;odd=odd.next;even.next=odd.next;even=even.next;}odd.next=evenHead;return head;}}',
python_code:'def oddEvenList(head):\n    if not head or not head.next: return head\n    odd=head;even=head.next;evenHead=even\n    while even and even.next:\n        odd.next=even.next;odd=odd.next\n        even.next=odd.next;even=even.next\n    odd.next=evenHead\n    return head',
cpp_code:'ListNode* oddEvenList(ListNode* head){if(!head||!head->next)return head;auto odd=head,even=head->next,evenHead=even;while(even&&even->next){odd->next=even->next;odd=odd->next;even->next=odd->next;even=even->next;}odd->next=evenHead;return head;}',
companies:['Amazon'],tags:['LinkedList'],similarQs:['Reorder List'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two chain split',trick:'Build both chains simultaneously, merge at end',leetcodeUrl:'https://leetcode.com/problems/odd-even-linked-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:19,globalOrder:59,title:'Partition List',difficulty:'Medium',
description:'Partition list so nodes less than x come before nodes >= x.',
examples:[{input:'head=[1,4,3,2,5,2], x=3',output:'[1,2,2,4,3,5]'}],
hint:'Build two separate lists, then join.',approach:'Maintain two dummy lists (less, greaterEqual), append accordingly, then connect.',
java_code:'class Solution{public ListNode partition(ListNode head,int x){ListNode lessDummy=new ListNode(0),geDummy=new ListNode(0);ListNode less=lessDummy,ge=geDummy;while(head!=null){if(head.val<x){less.next=head;less=less.next;}else{ge.next=head;ge=ge.next;}head=head.next;}ge.next=null;less.next=geDummy.next;return lessDummy.next;}}',
python_code:'def partition(head,x):\n    lessDummy=ListNode(0);geDummy=ListNode(0)\n    less,ge=lessDummy,geDummy\n    while head:\n        if head.val<x: less.next=head;less=less.next\n        else: ge.next=head;ge=ge.next\n        head=head.next\n    ge.next=None;less.next=geDummy.next\n    return lessDummy.next',
cpp_code:'ListNode* partition(ListNode* head,int x){ListNode lessDummy(0),geDummy(0);auto less=&lessDummy,ge=&geDummy;while(head){if(head->val<x){less->next=head;less=less->next;}else{ge->next=head;ge=ge->next;}head=head->next;}ge->next=nullptr;less->next=geDummy.next;return lessDummy.next;}',
companies:['Amazon'],tags:['LinkedList'],similarQs:['Sort List'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Two-list partition',trick:'Build less and ge chains in single pass',leetcodeUrl:'https://leetcode.com/problems/partition-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:20,globalOrder:60,title:'Sort List',difficulty:'Medium',
description:'Sort a linked list in O(n log n) time using constant space.',
examples:[{input:'head=[4,2,1,3]',output:'[1,2,3,4]'}],
hint:'Merge sort on linked list.',approach:'Split list into halves recursively, merge sorted halves.',
java_code:'class Solution{public ListNode sortList(ListNode head){if(head==null||head.next==null)return head;ListNode slow=head,fast=head.next;while(fast!=null&&fast.next!=null){slow=slow.next;fast=fast.next.next;}ListNode mid=slow.next;slow.next=null;ListNode left=sortList(head),right=sortList(mid);return merge(left,right);}ListNode merge(ListNode a,ListNode b){ListNode dummy=new ListNode(0),cur=dummy;while(a!=null&&b!=null){if(a.val<=b.val){cur.next=a;a=a.next;}else{cur.next=b;b=b.next;}cur=cur.next;}cur.next=(a!=null)?a:b;return dummy.next;}}',
python_code:'def sortList(head):\n    if not head or not head.next: return head\n    slow,fast=head,head.next\n    while fast and fast.next:\n        slow=slow.next;fast=fast.next.next\n    mid=slow.next;slow.next=None\n    left=sortList(head);right=sortList(mid)\n    dummy=cur=ListNode(0)\n    while left and right:\n        if left.val<=right.val: cur.next=left;left=left.next\n        else: cur.next=right;right=right.next\n        cur=cur.next\n    cur.next=left or right\n    return dummy.next',
cpp_code:'ListNode* merge(ListNode* a,ListNode* b){ListNode dummy(0);auto cur=&dummy;while(a&&b){if(a->val<=b->val){cur->next=a;a=a->next;}else{cur->next=b;b=b->next;}cur=cur->next;}cur->next=a?a:b;return dummy.next;}ListNode* sortList(ListNode* head){if(!head||!head->next)return head;auto slow=head,fast=head->next;while(fast&&fast->next){slow=slow->next;fast=fast->next->next;}auto mid=slow->next;slow->next=nullptr;auto left=sortList(head),right=sortList(mid);return merge(left,right);}',
companies:['Amazon','Microsoft'],tags:['LinkedList','Sorting'],similarQs:['Merge Two Sorted Lists'],timeComplex:'O(n log n)',spaceComplex:'O(log n)',pattern:'Merge sort on list',trick:'Slow-fast finds midpoint for splitting',leetcodeUrl:'https://leetcode.com/problems/sort-list/'},

{topicSlug:'linkedlist',topic:'Linked List',order:21,globalOrder:61,title:'Remove Linked List Elements',difficulty:'Easy',
description:'Remove all nodes with a given value from a linked list.',
examples:[{input:'head=[1,2,6,3,4,5,6], val=6',output:'[1,2,3,4,5]'}],
hint:'Use dummy node to handle head removal too.',approach:'Traverse with dummy.next=head, skip nodes matching val.',
java_code:'class Solution{public ListNode removeElements(ListNode head,int val){ListNode dummy=new ListNode(0);dummy.next=head;ListNode cur=dummy;while(cur.next!=null){if(cur.next.val==val)cur.next=cur.next.next;else cur=cur.next;}return dummy.next;}}',
python_code:'def removeElements(head,val):\n    dummy=ListNode(0);dummy.next=head;cur=dummy\n    while cur.next:\n        if cur.next.val==val: cur.next=cur.next.next\n        else: cur=cur.next\n    return dummy.next',
cpp_code:'ListNode* removeElements(ListNode* head,int val){ListNode dummy(0);dummy.next=head;auto cur=&dummy;while(cur->next){if(cur->next->val==val)cur->next=cur->next->next;else cur=cur->next;}return dummy.next;}',
companies:['TCS','Amazon'],tags:['LinkedList'],similarQs:['Remove Duplicates from Sorted List'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Dummy node traversal',trick:'Dummy node handles deleting the head node cleanly',leetcodeUrl:'https://leetcode.com/problems/remove-linked-list-elements/'},

{topicSlug:'linkedlist',topic:'Linked List',order:22,globalOrder:62,title:'Convert Binary Number in a Linked List to Integer',difficulty:'Easy',
description:'Given head representing a binary number, return its decimal value.',
examples:[{input:'head=[1,0,1]',output:'5'}],
hint:'Shift left and add each bit.',approach:'Traverse list, result = result*2 + node.val for each node.',
java_code:'class Solution{public int getDecimalValue(ListNode head){int res=0;while(head!=null){res=res*2+head.val;head=head.next;}return res;}}',
python_code:'def getDecimalValue(head):\n    res=0\n    while head:\n        res=res*2+head.val;head=head.next\n    return res',
cpp_code:'int getDecimalValue(ListNode* head){int res=0;while(head){res=res*2+head->val;head=head->next;}return res;}',
companies:['TCS','Amazon'],tags:['LinkedList','Math'],similarQs:['Binary to Decimal'],timeComplex:'O(n)',spaceComplex:'O(1)',pattern:'Bit accumulation',trick:'res*2+bit builds binary number like manual conversion',leetcodeUrl:'https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer/'},
];

async function seed() {
  await MasterDSAQuestion.deleteMany({});
  const inserted = await MasterDSAQuestion.insertMany(questions);
  console.log(`✅ Inserted ${inserted.length} Master DSA questions`);
  mongoose.disconnect();
}

seed().catch(err => { console.error(err); mongoose.disconnect(); });
